import type { LaunchKnob } from "./types";

export const LAUNCH_KNOBS: readonly LaunchKnob[] = [
  {
    wire: "ctx-size",
    label: "Context size",
    group: "Start settings",
    level: "start",
    kind: "integer",
    whatItIs: "Context size is how much of the conversation the model can hold while answering.",
    whatItsFor: "A larger context can keep more earlier conversation available but uses more memory; this app calculates the safe automatic value for the chosen model and computer.",
    usualValues: "A chat-sized default is usual here — 64k where this computer funds it. The panel shows what the KV cache costs for the value chosen, and the machine's maximum is one click away.",
  },
  {
    wire: "batch-size",
    label: "Batch size",
    group: "Start settings",
    level: "start",
    kind: "integer",
    min: 64,
    max: 8192,
    step: 1,
    whatItIs: "Batch size is how many prompt pieces the server groups into one logical processing job.",
    whatItsFor: "Larger batches can process the prompt faster but need more working memory; this setting affects start-up processing, not the assistant’s wording.",
    usualValues: "2048 here; the shipped run reached 1883 tokens/s versus 1151 at the old 512.",
  },
  {
    wire: "ubatch-size",
    label: "Micro-batch size",
    group: "Start settings",
    level: "start",
    kind: "integer",
    min: 64,
    max: 1024,
    step: 1,
    whatItIs: "Micro-batch size is how many prompt pieces the server handles in one physical memory step.",
    whatItsFor: "Larger steps can improve prompt speed but use more compute-buffer memory; this computer’s measured budget limits the useful setting.",
    usualValues: "512 default; 1024 fits at 346.6–414.0 MiB at 16k; 2048 costs 602.7 MiB at 4096.",
  },
  {
    wire: "cache-type-k/cache-type-v",
    label: "KV cache type",
    group: "Start settings",
    level: "start",
    kind: "choice",
    options: ["q8_0", "f16"],
    whatItIs: "KV cache type chooses the precision used to remember earlier conversation inside the model.",
    whatItsFor: "q8_0 uses less memory but can lose a little cache precision; f16 keeps more precision but costs twice per cache element and roughly halves this computer’s funded context.",
    usualValues: "q8_0 is usual here; choose f16 when preserving cache precision matters more than context length.",
  },
  {
    wire: "sleep-idle-seconds",
    label: "Unload after idle",
    group: "Start settings",
    level: "start",
    kind: "integer",
    min: 60,
    max: 3600,
    step: 60,
    whatItIs: "This is how long the unused model and its conversation cache stay loaded before the server releases them.",
    whatItsFor: "A shorter time frees memory sooner but reloads more often; a longer time keeps the next message ready but holds memory while idle. Either way the next message loads the model back.",
    usualValues: "5 minutes is the app default. The choices are 1 minute, 5 minutes and 1 hour.",
  },
  {
    wire: "internet_road",
    label: "Internet road",
    group: "Start settings",
    level: "start",
    kind: "boolean",
    options: ["off", "on"],
    whatItIs: "Internet road is this app’s optional iroh connection that gives the phone a second way to reach the computer.",
    whatItsFor: "Turn it on only when the phone cannot use the other road; it announces the computer on a public directory service, while the door still checks its password.",
    usualValues: "Off, unless the phone cannot reach the computer another way.",
  },
];
