import type { SamplingKnob } from "./types";

const INT32_MAX = 2_147_483_647;

export const SAMPLING_KNOBS: readonly SamplingKnob[] = [
  {
    wire: "temperature",
    label: "Temperature",
    group: "Randomness",
    level: "message",
    kind: "number",
    // The schema has no upper limit; this is a generous UI guard rail, not a measurement.
    min: 0,
    max: 10,
    step: 0.01,
    whatItIs: "Temperature controls how freely the model chooses among possible next pieces of text.",
    whatItsFor: "Higher values make replies more varied and less predictable; lower values make them steadier and more repeatable.",
    usualValues: "0.8 is the current llama.cpp starting point; lower values suit steadier answers.",
  },
  {
    wire: "dynatemp_range",
    label: "Dynamic temperature range",
    group: "Randomness",
    level: "message",
    kind: "number",
    // No schema upper limit; this is a generous UI guard rail, not a measurement.
    min: 0,
    max: 10,
    step: 0.01,
    whatItIs: "This is the most temperature may move up or down when the model judges the next choice more or less predictable.",
    whatItsFor: "It can add variety when the model is confident and restraint when it is uncertain; zero leaves temperature fixed.",
    usualValues: null,
  },
  {
    wire: "dynatemp_exponent",
    label: "Dynamic temperature exponent",
    group: "Randomness",
    level: "message",
    kind: "number",
    min: 0,
    max: 10,
    step: 0.01,
    whatItIs: "This controls how strongly the model’s uncertainty changes the dynamic temperature.",
    whatItsFor: "It changes where the adjustment sits between the lower and upper temperature limits; it does not itself set the limits.",
    usualValues: null,
  },
  {
    wire: "top_k",
    label: "Top K",
    group: "Randomness",
    level: "message",
    kind: "integer",
    min: 0,
    max: INT32_MAX,
    step: 1,
    whatItIs: "Top K limits the next choice to the K most likely pieces of text.",
    whatItsFor: "Lower values make answers more predictable; higher values leave more alternatives, which can add variety and mistakes.",
    usualValues: "40 is the llama.cpp starting point; 0 disables this limit.",
  },
  {
    wire: "top_p",
    label: "Top P",
    group: "Randomness",
    level: "message",
    kind: "number",
    min: 0,
    max: 1,
    step: 0.01,
    whatItIs: "Top P keeps the smallest group of likely next choices whose combined probability reaches P.",
    whatItsFor: "Lower values narrow the answer towards likely wording; higher values allow more unusual wording and ideas.",
    usualValues: "0.9 is used in Llama 2; current llama.cpp uses 0.95 as its baseline.",
  },
  {
    wire: "min_p",
    label: "Minimum probability",
    group: "Randomness",
    level: "message",
    kind: "number",
    min: 0,
    max: 1,
    step: 0.01,
    whatItIs: "Minimum probability removes a choice that is below P times the probability of the most likely choice.",
    whatItsFor: "It filters out weak alternatives while keeping the cutoff relative to the model’s confidence, so answers can stay varied without wandering.",
    usualValues: "0.05 is the llama.cpp starting point; 0 disables this filter.",
  },
  {
    wire: "typical_p",
    label: "Typical probability",
    group: "How much it trims",
    level: "message",
    kind: "number",
    // No schema limit; these are UI guard rails, not measurements.
    min: 0,
    max: 1,
    step: 0.01,
    whatItIs: "Typical probability favours choices whose likelihood is close to the model’s usual likelihood for this point in the answer.",
    whatItsFor: "It can reduce dull loops while keeping natural alternatives; 1.0 leaves this sampler disabled.",
    usualValues: null,
  },
  {
    wire: "top_n_sigma",
    label: "Top N spread",
    group: "How much it trims",
    level: "message",
    kind: "number",
    // No schema limit; these are UI guard rails, not measurements.
    min: -1,
    max: 10,
    step: 0.01,
    whatItIs: "Top N spread keeps choices within N measures of score spread from the best choice.",
    whatItsFor: "It removes choices far below the best score; negative values disable this filter.",
    usualValues: null,
  },
  {
    wire: "xtc_probability",
    label: "Exclude top choices chance",
    group: "How much it trims",
    level: "message",
    kind: "number",
    min: 0,
    max: 1,
    step: 0.01,
    whatItIs: "XTC, or Exclude Top Choices, is the chance of removing some of the most likely choices.",
    whatItsFor: "It can break predictable wording and repeated patterns; higher values make that intervention happen more often.",
    usualValues: null,
  },
  {
    wire: "xtc_threshold",
    label: "Exclude top choices threshold",
    group: "How much it trims",
    level: "message",
    kind: "number",
    min: 0,
    max: 1,
    step: 0.01,
    whatItIs: "This is the minimum probability a choice must have before XTC may remove it.",
    whatItsFor: "Lower values let XTC affect more choices; values above 0.5 turn XTC off in this server.",
    usualValues: null,
  },
  {
    wire: "min_keep",
    label: "Minimum kept choices",
    group: "How much it trims",
    level: "message",
    kind: "integer",
    min: 0,
    max: INT32_MAX,
    step: 1,
    whatItIs: "Minimum kept choices prevents the other samplers from reducing the possible next choices below this number.",
    whatItsFor: "It provides a safety floor when several filters are combined; 0 lets each sampler decide freely.",
    usualValues: "0 is the baseline; active values are normally chosen only for a specific sampler setup.",
  },
  {
    wire: "repeat_penalty",
    label: "Repetition penalty",
    group: "Repetition",
    level: "message",
    kind: "number",
    // No schema limit; these are UI guard rails, not measurements.
    min: 0,
    max: 5,
    step: 0.01,
    whatItIs: "Repetition penalty lowers the chance of text pieces already used in the recent answer.",
    whatItsFor: "Values above 1 can reduce repeated phrases; 1 leaves the penalty disabled, while values below 1 can encourage repetition.",
    usualValues: "1.0 is the llama.cpp baseline; some llama.cpp examples use 1.1.",
  },
  {
    wire: "repeat_last_n",
    label: "Repetition lookback",
    group: "Repetition",
    level: "message",
    kind: "integer",
    min: 0,
    max: INT32_MAX,
    step: 1,
    whatItIs: "Repetition lookback says how many recent text pieces the repetition penalty can inspect.",
    whatItsFor: "A larger lookback catches older repeated wording but can make a reply less faithful to its own established phrasing; 0 disables it.",
    usualValues: "64 is the llama.cpp baseline; 0 disables the penalty.",
  },
  {
    wire: "frequency_penalty",
    label: "Frequency penalty",
    group: "Repetition",
    level: "message",
    kind: "number",
    // No schema limit; these are UI guard rails, not measurements.
    min: -5,
    max: 5,
    step: 0.01,
    whatItIs: "Frequency penalty lowers a choice more each time the same text piece has already appeared.",
    whatItsFor: "It can discourage repeated words and phrases; 0 leaves it disabled.",
    usualValues: "0 is the llama.cpp baseline; active values depend on the model and task.",
  },
  {
    wire: "presence_penalty",
    label: "Presence penalty",
    group: "Repetition",
    level: "message",
    kind: "number",
    // No schema limit; these are UI guard rails, not measurements.
    min: -5,
    max: 5,
    step: 0.01,
    whatItIs: "Presence penalty lowers a choice simply because the same text piece has appeared before.",
    whatItsFor: "It can encourage the answer to introduce different words and topics; 0 leaves it disabled.",
    usualValues: "0 is the llama.cpp baseline; active values depend on the model and task.",
  },
  {
    wire: "dry_multiplier",
    label: "DRY repetition multiplier",
    group: "Repetition",
    level: "message",
    kind: "number",
    // No schema limit; these are UI guard rails, not measurements.
    min: 0,
    max: 10,
    step: 0.01,
    whatItIs: "DRY, or Don’t Repeat Yourself, controls the strength of a penalty for extending repeated text sequences.",
    whatItsFor: "It targets longer repeated phrases, including repetitions that ordinary recent-word penalties may miss; 0 disables it.",
    usualValues: null,
  },
  {
    wire: "dry_base",
    label: "DRY base",
    group: "Repetition",
    level: "message",
    kind: "number",
    // No schema limit; this is a UI guard rail, not a measurement.
    min: 1,
    max: 10,
    step: 0.01,
    whatItIs: "DRY base controls how quickly the DRY penalty grows as a repeated sequence gets longer.",
    whatItsFor: "A larger base makes long repetitions increasingly costly; values below 1 are replaced by the build’s default.",
    usualValues: "1.75 is the llama.cpp baseline; no broader active value is established.",
  },
  {
    wire: "dry_allowed_length",
    label: "DRY allowed length",
    group: "Repetition",
    level: "message",
    kind: "integer",
    min: 0,
    max: INT32_MAX,
    step: 1,
    whatItIs: "DRY allowed length is how long a repeated sequence may become before the DRY penalty starts.",
    whatItsFor: "Raising it tolerates longer repeated phrases; lowering it reacts sooner and can make wording less natural.",
    usualValues: "2 is the llama.cpp baseline; task-specific tuning has no agreed standard.",
  },
  {
    wire: "dry_penalty_last_n",
    label: "DRY lookback",
    group: "Repetition",
    level: "message",
    kind: "integer",
    min: 0,
    max: INT32_MAX,
    step: 1,
    whatItIs: "DRY lookback says how many recent text pieces DRY scans for repeated sequences.",
    whatItsFor: "A larger lookback can catch older repetitions but costs more attention to history; 0 disables DRY’s penalty.",
    usualValues: "64 is the llama.cpp baseline; 0 disables the penalty.",
  },
  {
    wire: "mirostat",
    label: "Mirostat mode",
    group: "Alternative samplers",
    level: "message",
    kind: "integer",
    min: 0,
    max: 2,
    step: 1,
    whatItIs: "Mirostat adjusts its choices while writing to keep the answer near a chosen level of surprise.",
    whatItsFor: "It can balance predictable and varied writing over time; 0 disables it, while 1 and 2 select its two versions.",
    usualValues: "0 is the baseline; there is no agreed enabled choice for every model.",
  },
  {
    wire: "mirostat_tau",
    label: "Mirostat target",
    group: "Alternative samplers",
    level: "message",
    kind: "number",
    // No schema limit; zero has no useful target-entropy meaning here.
    min: 0.01,
    max: 20,
    step: 0.01,
    whatItIs: "Mirostat target is the desired average surprise of the model’s choices, measured by how unexpected they are.",
    whatItsFor: "Higher values aim for more surprising, varied answers; lower values aim for more predictable answers.",
    usualValues: "5.0 is the llama.cpp baseline; there is no universal target across models.",
  },
  {
    wire: "mirostat_eta",
    label: "Mirostat learning rate",
    group: "Alternative samplers",
    level: "message",
    kind: "number",
    // No schema limit; these are UI guard rails, not measurements.
    min: 0,
    max: 1,
    step: 0.01,
    whatItIs: "Mirostat learning rate controls how quickly Mirostat reacts when its recent surprise differs from the target.",
    whatItsFor: "Higher values react faster and can vary more; lower values react more gently and can take longer to settle.",
    usualValues: "0.1 is the llama.cpp baseline; there is no universal rate across models.",
  },
  {
    wire: "adaptive_target",
    label: "Adaptive target",
    group: "Alternative samplers",
    level: "message",
    kind: "number",
    // The server accepts float32 minimum; this is that limit, not a UI invention.
    min: -3.4028234663852886e38,
    max: 1,
    step: 0.01,
    whatItIs: "Adaptive target asks the sampler to favour choices near a chosen probability, adapting that target as the answer continues.",
    whatItsFor: "It is intended to balance variety and predictability over time; negative values disable adaptive sampling.",
    usualValues: null,
  },
  {
    wire: "adaptive_decay",
    label: "Adaptive decay",
    group: "Alternative samplers",
    level: "message",
    kind: "number",
    min: 0,
    max: 0.99,
    step: 0.01,
    whatItIs: "Adaptive decay controls how much recent choices outweigh older choices when adaptive sampling updates its target.",
    whatItsFor: "Higher values remember more history and change gently; lower values respond more quickly to the latest choices.",
    usualValues: null,
  },
  {
    wire: "seed",
    label: "Random seed",
    group: "This answer",
    level: "message",
    kind: "integer",
    // No schema numeric limit; these are UI guard rails, and sentinels stay automatic.
    min: 0,
    max: INT32_MAX,
    step: 1,
    whatItIs: "The random seed starts the choices used when more than one answer is possible.",
    whatItsFor: "A fixed seed can repeat a run with the same inputs; the random setting avoids making every run follow the same choices.",
    usualValues: "Random is usual; use a fixed integer when you need repeatable tests.",
    automaticSentinels: [-1, 4_294_967_295],
    automaticDescription: "Automatic picks a new seed for every message, so the same question can get a different answer.",
  },
  {
    wire: "max_tokens",
    label: "Maximum new tokens",
    group: "This answer",
    level: "message",
    kind: "integer",
    min: -1,
    max: INT32_MAX,
    step: 1,
    whatItIs: "This is the maximum amount of new text the assistant may produce for one message.",
    whatItsFor: "A smaller limit ends long replies sooner; leaving it automatic lets the server's output length remain unlimited.",
    usualValues: null,
  },
];
