const config = {
  name: "Kalsa AI Chat",
  slug: "kalsa",
  version: "0.1.0",
  orientation: "portrait",
  scheme: "kalsa",
  // Neural-leaf mark (owner's logo, 2026-08-07). Source JPEG lives in
  // Desktop/Kalsa; assets regenerated by the scratchpad make_icon.py flow
  // (leaf extracted, K-column lockup dropped — icons carry one idea).
  icon: "./assets/icon.png",
  userInterfaceStyle: "automatic",
  assetBundlePatterns: ["**/*"],
  ios: {
    supportsTablet: true,
    bundleIdentifier: "com.kalsa.app",
    deploymentTarget: "16.4",
    config: {
      usesNonExemptEncryption: false,
    },
    infoPlist: {
      NSMicrophoneUsageDescription:
        "Kalsa uses the microphone for on-device voice dictation. Audio stays on this device.",
      NSCalendarsUsageDescription:
        "Kalsa reads your calendar to answer agenda questions on this device. Events stay on the device.",
      NSCalendarsFullAccessUsageDescription:
        "Kalsa reads your calendar to answer agenda questions on this device. Events stay on the device.",
      // Without this, Core Animation stays at 60Hz on iPhone (iPad Pro does not need it).
      CADisableMinimumFrameDurationOnPhone: true,
    },
  },
  android: {
    package: "com.kalsa.app",
    permissions: ["android.permission.RECORD_AUDIO", "android.permission.READ_CALENDAR"],
    intentFilters: [
      {
        action: "android.intent.action.SEND",
        category: ["android.intent.category.DEFAULT"],
        data: [{ mimeType: "text/plain" }],
      },
      {
        action: "android.intent.action.SEND",
        category: ["android.intent.category.DEFAULT"],
        data: [{ mimeType: "application/pdf" }],
      },
      {
        action: "android.intent.action.SEND_MULTIPLE",
        category: ["android.intent.category.DEFAULT"],
        data: [{ mimeType: "text/plain" }],
      },
      {
        action: "android.intent.action.SEND_MULTIPLE",
        category: ["android.intent.category.DEFAULT"],
        data: [{ mimeType: "application/pdf" }],
      },
    ],
    allowBackup: false,
    usesCleartextTraffic: false,
    adaptiveIcon: {
      // Leaf sized to the ~62% safe zone: launchers crop to circle/squircle.
      foregroundImage: "./assets/adaptive-icon.png",
      backgroundColor: "#07110F",
    },
  },
  extra: {
    // Tutto locale: nessun backend. Endpoint opzionali futuri vanno qui.
  },
  plugins: [
    "./plugins/withLintOff",
    "./plugins/withDisplayRefreshRate",
    "./plugins/withAndroidShareIntent",
    "expo-font",
    "expo-secure-store",
    "expo-sharing",
    [
      "expo-image-picker",
      {
        photosPermission: "AI Chat lets you attach photos so the local model can read them.",
        cameraPermission: "AI Chat uses the camera to take photos for the local model.",
      },
    ],
    [
      "expo-notifications",
      {
        color: "#0b1512",
      },
    ],
    [
      "llama.rn",
      {
        enableEntitlements: true,
        entitlementsProfile: "production",
        forceCxx20: true,
        enableOpenCLAndHexagon: true,
      },
    ],
    "./plugins/withGovernorBattery",
    [
      "expo-build-properties",
      {
        android: {
          newArchEnabled: true,
          // Ship policy (owner, 2026-08-22): Android 13+ — REVERSES the
          // 2026-08-07 "Android 15+ ONLY" decision, which made the app
          // uninstallable on half the measurement lab (the Jelly Star is
          // API 33, and INSTALL_FAILED_OLDER_SDK is what surfaced this).
          //
          // What the old floor bought, and is now back in scope: edge-to-edge
          // is not mandatory below API 35, keyboard-controller does not always
          // compute the full IME height there, and the API<=34 nav-bar
          // shortfall class is no longer excluded by construction. Those are
          // layout defects to fix when they appear, not reasons to refuse the
          // install.
          minSdkVersion: 33,
        },
      },
    ],
    // Compiles llama.rn cpp/ by default so patches/llama.rn+*.patch take effect.
    // Opt out with KALSA_LLAMA_FROM_SOURCE=0 (prebuilt jniLibs). See plugin header.
    "./plugins/withLlamaFromSource",
    [
      "expo-calendar",
      {
        calendarPermission:
          "Kalsa reads your calendar to answer agenda questions on this device. Events stay on the device.",
      },
    ],
    "./plugins/withCalendarReadOnly",
  ],
};

module.exports = () => {
  const next = JSON.parse(JSON.stringify(config));
  return next;
};
