#!/usr/bin/env node
/**
 * Writes workers/download/guide.ts from the tester guide markdown.
 *
 *   node scripts/build-guide.mjs <ALPHA-TESTERS.md> [--check]
 *
 * --check exits 1 when the committed guide.ts is not what the markdown produces.
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { parseBlocks, renderBlock } from "./markdown-subset.mjs";

const OUT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../guide.ts");

// The page links #mac and #windows, so those two install sections keep their names.
const SECTION_IDS = {
  1: "requirements",
  2: "mac",
  3: "windows",
  4: "first-start",
  5: "phone",
  6: "problems",
  8: "uninstall",
};
// Section 7 is the download page itself, so the guide does not repeat it.
const DROPPED = new Set([7]);

function sectionNumber(text) {
  const match = /^(\d+)\. /.exec(text);
  return match ? Number(match[1]) : null;
}

function guideLines(source) {
  const lines = [];
  const seen = new Set();
  let dropping = false;
  for (const block of parseBlocks(source)) {
    if (block.type === "h1") continue;
    if (block.type === "h2") {
      const number = sectionNumber(block.text);
      if (number === null) throw new Error(`unnumbered section: ${block.text}`);
      dropping = DROPPED.has(number);
      if (dropping) continue;
      if (!(number in SECTION_IDS)) throw new Error(`no anchor for section ${number}`);
      seen.add(number);
      lines.push(renderBlock(block, SECTION_IDS[number]));
      continue;
    }
    if (!dropping) lines.push(renderBlock(block));
  }
  for (const number of Object.keys(SECTION_IDS)) {
    if (!seen.has(Number(number))) throw new Error(`section ${number} missing from the markdown`);
  }
  return lines;
}

function guideModule(source) {
  const body = guideLines(source).map((line) => `  ${JSON.stringify(line)},`).join("\n");
  return [
    "// Generated by scripts/build-guide.mjs from the tester guide markdown. Do not edit.",
    "export const GUIDE_HTML = [",
    body,
    '].join("\\n");',
    "",
  ].join("\n");
}

const args = process.argv.slice(2);
const check = args.includes("--check");
const [source] = args.filter((arg) => arg !== "--check");
if (!source) {
  console.error("usage: build-guide.mjs <ALPHA-TESTERS.md> [--check]");
  process.exit(2);
}

const expected = guideModule(readFileSync(source, "utf8"));
if (check) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {}
  if (current !== expected) {
    console.error(`guide.ts is out of date with ${source}; run scripts/build-guide.mjs`);
    process.exit(1);
  }
} else {
  writeFileSync(OUT, expected);
}
