/**
 * DEV phone vehicle: keep the CI release variant debuggable for run-as
 * sideloading. The Android project is generated by Expo, so patch its Gradle
 * contents during prebuild instead of committing generated android/ files.
 */
const { withAppBuildGradle } = require("@expo/config-plugins");

module.exports = function withDebuggableRelease(config) {
  return withAppBuildGradle(config, (c) => {
    const buildTypesAt = c.modResults.contents.indexOf("buildTypes");
    if (buildTypesAt < 0) throw new Error("Kalsa: buildTypes block not found");

    const before = c.modResults.contents.slice(0, buildTypesAt);
    let after = c.modResults.contents.slice(buildTypesAt);
    if (/\brelease\s*\{[\s\S]*?\bdebuggable\s+true\b/.test(after)) return c;
    if (!/\brelease\s*\{/.test(after)) throw new Error("Kalsa: release build type not found");

    after = after.replace(/(\brelease\s*\{)/, "$1\n            debuggable true");
    c.modResults.contents = before + after;
    return c;
  });
};
