/**
 * DEV phone vehicle: keep the CI release variant debuggable for run-as
 * sideloading. The Android project is generated by Expo, so patch its Gradle
 * contents during prebuild instead of committing generated android/ files.
 */
const { withAppBuildGradle } = require("@expo/config-plugins");

module.exports = function withDebuggableRelease(config) {
  return withAppBuildGradle(config, (c) => {
    const buildTypesAt = c.modResults.contents.indexOf("buildTypes");
    if (buildTypesAt < 0) throw new Error("Kalsa: buildTypes block not found");

    const before = c.modResults.contents.slice(0, buildTypesAt);
    let after = c.modResults.contents.slice(buildTypesAt);
    const releaseBlock = /(^[ \t]*release\s*\{)([\s\S]{0,4096}?)(^[ \t]*\})/m.exec(after);
    if (!releaseBlock) throw new Error("Kalsa: release build type not found");
    if (/\bdebuggable\s+true\b/.test(releaseBlock[2])) return c;

    const patchedRelease = `${releaseBlock[1]}\n            debuggable true${releaseBlock[2]}${releaseBlock[3]}`;
    after =
      after.slice(0, releaseBlock.index) +
      patchedRelease +
      after.slice(releaseBlock.index + releaseBlock[0].length);
    c.modResults.contents = before + after;
    return c;
  });
};
