// Shared v2 wire contract. Desktop constants are generated by dev/generate-telemetry-spec.mjs.
export const V2 = {
  "description": "v2 preserves every v1 base field. Optional diagnostics is strictly allowlisted; absent means unobserved. POST /report JSON must be <=4096 UTF-8 bytes. Desktop emits v2; phones may keep v1. No identifiers, chats, text, URLs or paths. No arbitrary model/release strings.",
  "enums": {
    "component": [
      "engine",
      "door",
      "supervisor",
      "tune",
      "download",
      "room",
      "pairing",
      "web",
      "ui",
      "governor",
      "slots"
    ],
    "stage": [
      "load",
      "slot_restore",
      "prefill",
      "decode",
      "tool_call",
      "save",
      "wake",
      "stop",
      "download",
      "tune_measure",
      "other"
    ],
    "backend": [
      "metal",
      "vulkan",
      "cuda",
      "cpu",
      "opencl",
      "unknown"
    ],
    "offload": [
      "gpu",
      "cpu",
      "mixed"
    ],
    "modelId": [
      "2cba59c35d6c921d",
      "5aa3a7df6a68207f",
      "6cf2d69e925c832b",
      "abba3efbfbb7c48d",
      "c006505c9066c0b2",
      "c35de93deed24278",
      "c83a23693c5a5f28",
      "d555925adf131c6e",
      "ec36bdb5993373f7",
      "ee5739cd230cd118",
      "lfm2.5-2.6b",
      "multilingual-e5-small",
      "qwen3.5-4b",
      "whisper-tiny"
    ],
    "thermal": [
      "nominal",
      "fair",
      "serious",
      "critical",
      "unknown"
    ],
    "osFamily": [
      "windows",
      "macos",
      "linux",
      "android",
      "ios"
    ],
    "arch": [
      "x86_64",
      "aarch64",
      "x86",
      "arm",
      "unknown"
    ],
    "gpuVendor": [
      "apple",
      "nvidia",
      "amd",
      "intel",
      "qualcomm",
      "arm",
      "other"
    ]
  },
  "buckets": {
    "ramUse": {
      "edges": [
        50,
        75,
        90
      ],
      "labels": [
        "0-50",
        "50-75",
        "75-90",
        "90+"
      ],
      "why": "Pressure bands distinguish ordinary use from allocation risk; upper edges are exclusive."
    },
    "cpuLoad": {
      "edges": [
        50,
        75,
        90
      ],
      "labels": [
        "0-50",
        "50-75",
        "75-90",
        "90+"
      ],
      "why": "Use the same pressure bands as RAM to compare saturation without precise machine readings."
    },
    "freeRam": {
      "edges": [
        1073741824,
        4294967296,
        8589934592
      ],
      "labels": [
        "lt-1gb",
        "1-4gb",
        "4-8gb",
        "ge-8gb"
      ],
      "why": "GiB bands expose allocation headroom without exact memory sizes."
    },
    "ctxTokens": {
      "edges": [
        4096,
        16384,
        65536
      ],
      "labels": [
        "lt-4k",
        "4-16k",
        "16-64k",
        "ge-64k"
      ],
      "why": "Context capacity bands distinguish small, medium and long-context allocations."
    },
    "promptTokens": {
      "edges": [
        512,
        2048,
        8192
      ],
      "labels": [
        "lt-512",
        "512-2k",
        "2-8k",
        "ge-8k"
      ],
      "why": "Prompt bands locate prefill pressure without disclosing prompt content or exact length."
    },
    "tokensPerSecond": {
      "edges": [
        1,
        10,
        30
      ],
      "labels": [
        "lt-1",
        "1-10",
        "10-30",
        "ge-30"
      ],
      "why": "Rate bands distinguish stalls from usable decoding without precise device fingerprints."
    },
    "sinceStart": {
      "edges": [
        10,
        60,
        600
      ],
      "labels": [
        "lt-10s",
        "10-60s",
        "1-10m",
        "ge-10m"
      ],
      "why": "Elapsed bands separate launch failures from sustained use without wall-clock timestamps."
    },
    "deviceBucket": {
      "edges": [
        17179869184,
        34359738368
      ],
      "labels": [
        "low",
        "mid",
        "high"
      ],
      "why": "Desktop 16/32 GiB boundaries group model headroom rather than phone RAM capacity."
    }
  },
  "patterns": {
    "gpuModel": {
      "intel": "^(Intel\\(R\\) )?(Iris(\\(R\\))?( Xe)?( Plus)?( Graphics)?( [0-9]{3,4})?|UHD( Graphics)?( [0-9]{3,4})?|HD( Graphics)?( [0-9]{3,4})?|Arc(\\(TM\\))? [AB][0-9]{3}( Graphics)?)$",
      "amd": "^(AMD )?Radeon(\\(TM\\))? (RX [0-9]{3,4}( XT| XTX| GRE)?|[0-9]{3,4}M|Pro [A-Z]?[0-9]{3,4}(X)?|Graphics)$",
      "nvidia": "^NVIDIA (GeForce (RTX|GTX|GT) [0-9]{3,4}( Ti| SUPER)?( Laptop GPU)?|RTX [A-Z]?[0-9]{3,4}( Ada Generation)?|Quadro [A-Z]?[0-9]{3,4}|Tesla [A-Z][0-9]{2,3})$",
      "apple": "^Apple M[1-9][0-9]?( Pro| Max| Ultra)?$",
      "qualcomm": "^(Qualcomm )?Adreno(\\(TM\\))?( [0-9]{3,4}| X1-[0-9]{2})$",
      "arm": "^Mali-[GT][0-9]{2,3}( MP[0-9]{1,2})?$"
    },
    "cpuModel": "^(Intel(\\(R\\))? (Core(\\(TM\\))? (i[3579]-[0-9]{4,5}[A-Z]{0,3}|Ultra [3579] [0-9]{3}[A-Z]{0,2})|Celeron(\\(R\\))? [A-Z]?[0-9]{3,4}[A-Z]?|Pentium(\\(R\\))?( Gold| Silver)? [A-Z]?[0-9]{3,4}[A-Z]?)|AMD Ryzen [3579] [0-9]{4}[A-Z]{0,3}( [0-9]{1,2}-Core Processor)?|Apple M[1-9][0-9]?( Pro| Max| Ultra)?|(Qualcomm )?Snapdragon ([4-8](\\+)? Gen [1-9]|X (Elite|Plus))|A[0-9]{2}( Pro| Bionic)?)$",
    "gpuDriver": "^[0-9]{1,10}(\\.[0-9]{1,10}){1,5}$",
    "signature": "^(GGML_ASSERT (ggml|ggml-vulkan|ggml-metal|ggml-cuda|ggml-opencl|ggml-backend|llama|llama-context|server-context|server-slot)\\.(cpp|c|m|cu):[0-9]{1,7}|vk::(DeviceLostError|OutOfDeviceMemoryError|OutOfHostMemoryError|InitializationFailedError)|CUDA error|out of memory|segmentation fault)$",
    "assertLocation": "(?:^|[/\\\\\\s])(ggml(?:-vulkan|-metal|-cuda|-opencl|-backend)?|llama(?:-context)?|server-(?:context|slot))\\.(cpp|c|m|cu):([0-9]{1,7})\\b",
    "engineError": "\\bvk::(?:DeviceLostError|OutOfDeviceMemoryError|OutOfHostMemoryError|InitializationFailedError)\\b|\\bCUDA error\\b|\\bout of memory\\b|\\bsegmentation fault\\b",
    "engineRelease": "^v\\d+\\.\\d+\\.\\d+$",
    "logRef": "^[0-9]{4}-[0-9]{2}-[0-9]{2}/[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{8}$"
  },
  "limits": {
    "bodyBytes": 4096,
    "signatureChars": 80,
    "hardwareChars": 80,
    "breadcrumbs": 8,
    "exitCodeMin": -2147483648,
    "exitCodeMax": 4294967295,
    "exitSignalMin": 1,
    "exitSignalMax": 127
  },
  "rules": {
    "onBattery": "boolean, omit if unknown",
    "exitCode": "integer in limits; OS process status only",
    "exitSignal": "integer in limits; Unix signal only",
    "breadcrumbs": "array of <=8 objects with component and stage, optionally sinceStart; each entry is a state transition, no text or clock time",
    "signature": "On a line containing GGML_ASSERT, extract assertLocation (before or after ASSERT) and emit GGML_ASSERT basename:line. Otherwise extract engineError. Keep only source line numbers, max 80 characters; canonical signature must match signature pattern. Apply identifying-data redaction to the resulting token. No arbitrary filenames.",
    "hardware": "Apply existing redaction first, then full-match known naming shapes, ASCII <=80. gpuModel requires matching gpuVendor. gpuDriver is dotted numbers only, excluding four-part values whose parts are all <=255 (IPv4 literals). engineRelease matches ^v\\d+\\.\\d+\\.\\d+$ . Unknown naming shapes are omitted.",
    "modelId": "Exact public catalog tokens (desktop model_token FNV, including Q8 variants) or phone registry IDs. Never accept a syntactically plausible caller-supplied ID not in this list.",
    "logRef": "Optional. `<YYYY-MM-DD>/<ID>` naming the redacted log in the report Worker bucket: UTC day, then 8 chars of the report Worker id alphabet. Must match patterns.logRef exactly. Not part of the dedupe signature.",
    "offload": "Only emit observed gpu/cpu/mixed. An EngineFitted launch is not evidence of mixed offload.",
    "tokensPerSecond": "Rate of the observed stage; during prefill, processed tokens divided by engine-reported elapsed time. Omit on transition to decode unless a decode rate is observed.",
    "resources": "Most recent aggregate system RAM/CPU sample before the failure; sampling freezes on a failed engine so freed post-crash memory is not mistaken for failure headroom. Exact counters and elapsed times are never transmitted."
  },
  "base": {
    "required": [
      "v",
      "app",
      "appVersion",
      "platform",
      "deviceBucket",
      "osMajor",
      "error",
      "context",
      "dateBucket",
      "manual"
    ],
    "v": "2 (Worker also accepts v1 without diagnostics)",
    "app": "kalsa",
    "appVersion": "1-32 characters matching ^[0-9]+(\\.[0-9]+){1,3}[a-z0-9.-]*$",
    "platform": [
      "android",
      "ios",
      "windows",
      "macos",
      "linux"
    ],
    "deviceBucket": [
      "low",
      "mid",
      "high"
    ],
    "osMajor": "1-8 decimal digits; 0 when unknown",
    "dateBucket": "calendar-valid UTC YYYY-MM-DD; daily, not precise time",
    "manual": "boolean; false for automatic desktop errors",
    "error": "object with required code, optional detail and signal; no other keys",
    "codes": [
      "engine.init",
      "chat.generation",
      "embed.native",
      "web.fetch",
      "web.search",
      "unknown"
    ],
    "details": "Per-code v1 detail sets in schema.ts, unchanged. unknown accepts only unknown.",
    "signal": "Only canonical v1 SIGNAL_FIXED tokens in schema.ts; any ggml_<id> normalizes to ggml_*. No free text.",
    "context": "Only optional modelCategory, memoryClass, hadWebTools, phase, attempt, chunks; v1 validation unchanged.",
    "modelCategory": [
      "dense.2b",
      "dense.4b",
      "moe",
      "unknown"
    ],
    "memoryClass": [
      "lt-4gb",
      "4-6gb",
      "ge-6gb",
      "unknown"
    ],
    "phase": [
      "download",
      "load",
      "turn",
      "embed",
      "flush"
    ],
    "attempt": "integer 1-5",
    "chunks": "integer 0-100000, embed.native only",
    "diagnostics": "Optional object: enum and bucket fields below plus limits/rules fields. Unknown keys rejected at every nesting level. All diagnostics optional."
  }
} as const;
