import { Platform, StyleSheet } from "react-native";

import { glass } from "./glass";
import type { ThemeColors } from "./palettes";
import { DEFAULT_RESPONSIVE_METRICS } from "./responsiveMetrics";
import { radius, spacing } from "./tokens";

export type ResponsiveMetrics = typeof DEFAULT_RESPONSIVE_METRICS;

export function createStyles(colors: ThemeColors, metrics: ResponsiveMetrics = DEFAULT_RESPONSIVE_METRICS) {
  // Agora redesign fonts: Inter for body, Fraunces for display. Loaded via
  // useAgoraFonts (App.tsx blocks render until ready), so we can reference
  // these family names directly. Falls back to System if the load somehow
  // bypassed the gate (e.g. very early in render before the gate kicks in).
  const fontBody = "Inter_400Regular";
  const fontDisplay = "Fraunces_600SemiBold";
  const textClear = { includeFontPadding: false };
  const androidGlassSurface = Platform.OS === "android" ? colors.panelSolid : "transparent";
  return StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.shell,
  },
  appShell: {
    flex: 1,
    backgroundColor: "transparent",
  },
  blurTarget: {
    flex: 1,
    overflow: "hidden",
  },
  materialBackdrop: {
    ...(StyleSheet as any).absoluteFillObject,
    backgroundColor: colors.shell,
  },
  materialGrid: {
    ...(StyleSheet as any).absoluteFillObject,
    backgroundColor: colors.materialVeil,
    opacity: 0.48,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: metrics.horizontalPadding,
    paddingTop: metrics.topContentPadding,
    paddingBottom: metrics.contentBottomPadding,
  },
  topNoticeStack: {
    gap: spacing.xs,
    paddingTop: metrics.topContentPadding,
  },
  errorBanner: {
    alignItems: "center",
    backgroundColor: colors.panel,
    borderColor: colors.danger,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    marginHorizontal: spacing.lg,
    marginBottom: 0,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  errorText: {
    color: colors.danger,
    flex: 1,
    fontSize: 13,
    fontWeight: "800",
  },
  statusNotice: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    marginHorizontal: spacing.lg,
    marginBottom: 0,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  statusNoticeTitle: {
    ...textClear,
    fontSize: 13,
    fontWeight: "900",
  },
  statusNoticeDetail: {
    ...textClear,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
  },
  retryButton: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.md,
    borderWidth: 1,
    minHeight: 32,
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    paddingVertical: 0,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.10,
    shadowRadius: 12,
    elevation: 3,
  },
  retryButtonText: {
    ...textClear,
    color: colors.ink,
    fontSize: 12,
    fontWeight: "900",
  },
  askAssistantSheet: {
    bottom: metrics.askAssistantBottom,
    left: metrics.horizontalPadding,
    maxHeight: metrics.askAssistantMaxHeight,
    position: "absolute",
    right: metrics.horizontalPadding,
    zIndex: 40,
  },
  askAssistantPanel: {
    gap: spacing.md,
    maxHeight: metrics.askAssistantMaxHeight,
    padding: spacing.md,
  },
  askAssistantPanelChrome: {
    borderColor: colors.lineStrong,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 22 },
    shadowOpacity: 0.18,
    shadowRadius: 32,
    elevation: 10,
  },
  askAssistantHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  askAssistantIcon: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderRadius: radius.pill,
    borderColor: glass.hairline,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    elevation: 6,
    width: 42,
  },
  askAssistantHeaderCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  askAssistantTitle: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 16,
    fontWeight: "900",
  },
  askAssistantSubtitle: {
    ...textClear,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  askAssistantModeBadge: {
    backgroundColor: colors.panelBright,
    borderColor: colors.line,
    borderRadius: radius.pill,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
  },
  askAssistantModeText: {
    ...textClear,
    color: colors.accent,
    fontFamily: fontDisplay,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  askAssistantCloseButton: {
    alignItems: "center",
    backgroundColor: colors.panelBright,
    borderColor: colors.line,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  askAssistantMessages: {
    maxHeight: 190,
  },
  askAssistantMessageStack: {
    backgroundColor: colors.panelSoft,
    borderColor: colors.line,
    borderRadius: radius.lg,
    borderWidth: 1,
    maxHeight: 206,
    padding: spacing.xs,
  },
  askAssistantBubble: {
    borderRadius: radius.lg,
    marginBottom: spacing.xs,
    maxWidth: "86%",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 2,
  },
  askAssistantBubbleAssistant: {
    alignSelf: "flex-start",
    backgroundColor: colors.panelBright,
    borderColor: colors.line,
    borderWidth: 1,
  },
  askAssistantBubbleThinking: {
    borderColor: colors.accent,
    borderStyle: "dashed",
  },
  askAssistantBubbleStreaming: {
    borderColor: colors.accent,
  },
  askAssistantBubbleUser: {
    alignSelf: "flex-end",
    backgroundColor: colors.accent,
  },
  askAssistantBubbleText: {
    ...textClear,
    color: colors.ink,
    fontSize: 13,
    lineHeight: 18,
  },
  askAssistantBubbleUserText: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
  },
  askAssistantSources: {
    gap: 6,
    marginTop: spacing.sm,
  },
  askAssistantSourceCard: {
    backgroundColor: colors.panelSoft,
    borderColor: colors.line,
    borderRadius: radius.sm,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
  },
  askAssistantSourceTitle: {
    ...textClear,
    color: colors.ink,
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 14,
  },
  askAssistantSourceMeta: {
    ...textClear,
    color: colors.muted,
    fontSize: 10,
    lineHeight: 13,
    marginTop: 2,
  },
  miniappIosShell: {
    borderColor: "rgba(255,255,255,0.42)",
    borderRadius: 28,
    borderWidth: 1,
    elevation: 8,
    marginTop: spacing.sm,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 32,
  },
  miniappAndroidShell: {
    backgroundColor: "rgba(255,255,255,0.13)",
    borderColor: "rgba(255,255,255,0.22)",
    borderRadius: 28,
    borderWidth: 1,
    elevation: 12,
    marginTop: spacing.sm,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.22,
    shadowRadius: 22,
  },
  miniappVisionShell: {
    borderColor: "rgba(255,255,255,0.58)",
    borderRadius: 34,
    borderWidth: 1,
    elevation: 14,
    marginTop: spacing.sm,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.2,
    shadowRadius: 40,
  },
  miniappGlassOverlay: {
    ...(StyleSheet as any).absoluteFillObject,
  },
  miniappVisionHighlight: {
    backgroundColor: "rgba(255,255,255,0.72)",
    borderRadius: 999,
    height: 90,
    left: -20,
    opacity: 0.32,
    position: "absolute",
    top: -34,
    width: 190,
  },
  miniappAndroidGlow: {
    backgroundColor: "rgba(120,170,255,0.28)",
    borderRadius: 999,
    height: 150,
    opacity: 0.85,
    position: "absolute",
    right: -48,
    top: -52,
    width: 190,
  },
  miniappIosInner: {
    gap: spacing.md,
    padding: spacing.md,
  },
  miniappAndroidInner: {
    gap: spacing.md,
    padding: spacing.md,
  },
  miniappVisionInner: {
    gap: spacing.md,
    padding: spacing.lg,
  },
  miniappBlockSurfaceBase: {
    borderColor: "rgba(255,255,255,0.26)",
    borderRadius: 24,
    borderWidth: 1,
    overflow: "hidden",
  },
  miniappSurfaceHeroGlass: {
    backgroundColor: "rgba(255,255,255,0.20)",
    borderRadius: 28,
    padding: spacing.md,
  },
  miniappSurfaceMetricGlass: {
    backgroundColor: "rgba(255,255,255,0.14)",
    padding: spacing.sm,
  },
  miniappSurfaceScientificCanvas: {
    backgroundColor: "rgba(244,251,255,0.18)",
    minHeight: 150,
    padding: spacing.sm,
  },
  miniappSurfaceWellPlate: {
    backgroundColor: "rgba(246,252,255,0.16)",
    padding: spacing.sm,
  },
  miniappSurfaceDataSheet: {
    backgroundColor: "rgba(255,255,255,0.10)",
    padding: spacing.xs,
  },
  miniappSurfaceCommandBar: {
    backgroundColor: "rgba(255,255,255,0.16)",
    borderRadius: 999,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  miniappSurfaceFloatingControl: {
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: 22,
    padding: spacing.xs,
  },
  miniappSurfaceFrostedPanel: {
    backgroundColor: "rgba(255,255,255,0.12)",
    padding: spacing.sm,
  },
  miniappSurfaceDensityCompact: {
    marginTop: spacing.xs,
  },
  miniappSurfaceDensityComfortable: {
    marginTop: spacing.sm,
  },
  miniappSurfaceDensitySpacious: {
    marginTop: spacing.md,
  },
  miniappSurfaceAccentCyan: {
    borderLeftColor: "rgba(34,211,238,0.72)",
    borderLeftWidth: 3,
  },
  miniappSurfaceAccentIndigo: {
    borderLeftColor: "rgba(129,140,248,0.72)",
    borderLeftWidth: 3,
  },
  miniappSurfaceAccentLime: {
    borderLeftColor: "rgba(163,230,53,0.72)",
    borderLeftWidth: 3,
  },
  miniappSurfaceAccentRose: {
    borderLeftColor: "rgba(251,113,133,0.72)",
    borderLeftWidth: 3,
  },
  miniappSurfaceAccentViolet: {
    borderLeftColor: "rgba(196,181,253,0.72)",
    borderLeftWidth: 3,
  },
  miniappSurfaceAccentZinc: {
    borderLeftColor: "rgba(212,212,216,0.64)",
    borderLeftWidth: 3,
  },
  miniappSurfaceInteractive: {
    borderColor: "rgba(255,255,255,0.42)",
  },
  miniappSurfaceStateful: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 2,
  },
  miniappHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
  },
  miniappIconBadge: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.28)",
    borderColor: "rgba(255,255,255,0.48)",
    borderRadius: 999,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  miniappEyebrow: {
    ...textClear,
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  miniappTitle: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 17,
    fontWeight: "900",
    lineHeight: 22,
  },
  miniappSubtitle: {
    ...textClear,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
  },
  miniappHeroBlock: {
    gap: spacing.xs,
  },
  miniappBlockTitle: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 13,
    fontWeight: "900",
    lineHeight: 17,
  },
  miniappMetricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  miniappMetricCard: {
    backgroundColor: "rgba(255,255,255,0.24)",
    borderColor: "rgba(255,255,255,0.34)",
    borderRadius: 24,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: 120,
    padding: spacing.sm,
  },
  miniappMetricCardWide: {
    backgroundColor: "rgba(255,255,255,0.17)",
    borderColor: "rgba(255,255,255,0.30)",
    borderRadius: 24,
    borderWidth: 1,
    flexBasis: "100%",
    padding: spacing.sm,
  },
  miniappMetricLabel: {
    ...textClear,
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  miniappMetricValue: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 25,
    fontWeight: "900",
    lineHeight: 31,
    marginTop: 2,
  },
  miniappQualityText: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 18,
    fontWeight: "900",
    marginTop: 3,
  },
  miniappInputGrid: {
    gap: spacing.sm,
  },
  miniappInputCard: {
    backgroundColor: "rgba(255,255,255,0.18)",
    borderColor: "rgba(255,255,255,0.32)",
    borderRadius: 24,
    borderWidth: 1,
    padding: spacing.sm,
  },
  miniappInputLabel: {
    ...textClear,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
    marginBottom: 4,
  },
  miniappInput: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 18,
    fontWeight: "900",
    paddingVertical: 4,
  },
  miniappFormulaBox: {
    backgroundColor: "rgba(255,255,255,0.14)",
    borderColor: "rgba(255,255,255,0.28)",
    borderRadius: 24,
    borderWidth: 1,
    padding: spacing.sm,
  },
  miniappFormulaLabel: {
    ...textClear,
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  miniappFormulaText: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 13,
    fontWeight: "800",
    marginTop: 2,
  },
  miniappPlotBlock: {
    gap: spacing.xs,
  },
  miniappPlotFrame: {
    backgroundColor: "rgba(255,255,255,0.14)",
    borderColor: "rgba(255,255,255,0.28)",
    borderRadius: 24,
    borderWidth: 1,
    minHeight: 110,
    overflow: "hidden",
    padding: spacing.sm,
  },
  miniappPlotLine: {
    backgroundColor: colors.accent,
    borderRadius: 999,
    height: 3,
    marginTop: 54,
    opacity: 0.9,
    transform: [{ rotate: "-12deg" }],
    width: "84%",
  },
  miniappPlotText: {
    ...textClear,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
    marginTop: spacing.sm,
  },
  miniappTableBlock: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.24)",
    borderRadius: 24,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.sm,
  },
  miniappTableHeaderRow: {
    flexDirection: "row",
    gap: spacing.xs,
  },
  miniappTableRow: {
    flexDirection: "row",
    gap: spacing.xs,
  },
  miniappTableCell: {
    ...textClear,
    color: colors.primaryText,
    flex: 1,
    fontSize: 11,
    fontWeight: "700",
    minWidth: 40,
  },
  miniappTableHeaderCell: {
    color: colors.muted,
    fontWeight: "900",
  },
  miniappTableOverflowNotice: {
    ...textClear,
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
    marginTop: 2,
  },
  miniappPathwayScroller: {
    width: "100%",
  },
  miniappPathwayGraphViewport: {
    borderRadius: 22,
    overflow: "hidden",
    width: "100%",
  },
  miniappPathwayGraphViewportCompact: {
    maxHeight: 280,
  },
  miniappPathwayGraphViewportTablet: {
    maxHeight: 520,
  },
  miniappPathwayCanvas: {
    position: "relative",
    minHeight: 180,
  },
  miniappPathwayNode: {
    backgroundColor: "rgba(255,255,255,0.22)",
    borderColor: "rgba(255,255,255,0.45)",
    borderRadius: 16,
    borderWidth: 1,
    padding: spacing.sm,
    position: "absolute",
    width: 132,
  },
  miniappPathwayNodeCompact: {
    borderRadius: 14,
    padding: spacing.xs,
    width: 120,
  },
  miniappPathwayNodeTablet: {
    borderRadius: 18,
    padding: spacing.md,
    width: 164,
  },
  miniappPathwayNodeGene: {
    borderLeftColor: "rgba(34,211,238,0.95)",
    borderLeftWidth: 3,
  },
  miniappPathwayNodeProtein: {
    borderLeftColor: "rgba(129,140,248,0.95)",
    borderLeftWidth: 3,
  },
  miniappPathwayNodeDrug: {
    borderLeftColor: "rgba(251,113,133,0.95)",
    borderLeftWidth: 3,
  },
  miniappPathwayNodeProcess: {
    borderLeftColor: "rgba(163,230,53,0.95)",
    borderLeftWidth: 3,
  },
  miniappPathwayNodePhenotype: {
    borderLeftColor: "rgba(196,181,253,0.95)",
    borderLeftWidth: 3,
  },
  miniappPathwayNodeLabel: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  miniappPathwayNodeKind: {
    ...textClear,
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    marginTop: 1,
    textTransform: "uppercase",
  },
  miniappPathwayEdge: {
    position: "absolute",
    height: 2,
    left: 0,
    top: 0,
    backgroundColor: "rgba(148,163,184,0.8)",
  },
  miniappPathwayEdgeActivation: {
    opacity: 0.9,
    backgroundColor: "rgba(34,211,238,0.9)",
  },
  miniappPathwayEdgeInhibition: {
    opacity: 0.9,
    backgroundColor: "rgba(251,113,133,0.95)",
  },
  miniappPathwayEdgeBinding: {
    opacity: 0.9,
    backgroundColor: "rgba(196,181,253,0.9)",
  },
  miniappPathwayEdgeUnknown: {
    opacity: 0.62,
    backgroundColor: "rgba(148,163,184,0.9)",
  },
  miniappPathwayEdgeArrow: {
    borderLeftColor: "transparent",
    borderLeftWidth: 6,
    borderTopWidth: 5,
    borderBottomWidth: 5,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    height: 0,
    position: "absolute",
    width: 0,
  },
  miniappPathwayEdgeTerminus: {
    borderColor: "rgba(251,113,133,0.95)",
    borderRadius: 999,
    borderWidth: 2,
    height: 10,
    position: "absolute",
    width: 10,
  },
  miniappPathwayEdgeLabel: {
    ...textClear,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
    position: "absolute",
  },
  miniappPathwayEdgePressable: {
    minHeight: 44,
    minWidth: 44,
    position: "absolute",
  },
  miniappPathwaySelectedNode: {
    backgroundColor: "rgba(125,211,252,0.24)",
    borderColor: "rgba(186,230,253,0.96)",
    shadowColor: "#7dd3fc",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 6,
  },
  miniappPathwaySelectedEdge: {
    backgroundColor: "rgba(125,211,252,0.92)",
    shadowColor: "#7dd3fc",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.28,
    shadowRadius: 14,
    elevation: 5,
  },
  miniappPathwayEditorPanel: {
    backgroundColor: "rgba(255,255,255,0.16)",
    borderColor: "rgba(255,255,255,0.38)",
    borderRadius: 26,
    borderWidth: 1,
    elevation: 10,
    gap: spacing.sm,
    marginTop: spacing.sm,
    overflow: "hidden",
    padding: spacing.sm,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.16,
    shadowRadius: 28,
  },
  miniappPathwayEditorPanelCompact: {
    borderRadius: 22,
    padding: spacing.xs,
  },
  miniappPathwayEditorPanelTablet: {
    borderRadius: 28,
    padding: spacing.md,
  },
  miniappPathwayEditorSection: {
    backgroundColor: "rgba(255,255,255,0.13)",
    borderColor: "rgba(255,255,255,0.26)",
    borderRadius: 22,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.sm,
  },
  miniappPathwayEditorSectionTablet: {
    padding: spacing.md,
  },
  miniappPathwayEditorLabel: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 12,
    fontWeight: "900",
  },
  miniappPathwayEditorSmallLabel: {
    ...textClear,
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    marginTop: 4,
    textTransform: "uppercase",
  },
  miniappPathwayEditorInput: {
    ...textClear,
    backgroundColor: "rgba(255,255,255,0.20)",
    borderColor: "rgba(255,255,255,0.34)",
    borderRadius: 18,
    borderWidth: 1,
    color: colors.primaryText,
    fontSize: 14,
    fontWeight: "800",
    minHeight: 42,
    paddingHorizontal: spacing.sm,
    paddingVertical: 9,
  },
  miniappPathwayChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  miniappPathwayChip: {
    backgroundColor: "rgba(255,255,255,0.13)",
    borderColor: "rgba(255,255,255,0.28)",
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 44,
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
  },
  miniappPathwayChipActive: {
    backgroundColor: "rgba(34,211,238,0.22)",
    borderColor: "rgba(34,211,238,0.82)",
  },
  miniappPathwayMoveControls: {
    gap: spacing.xs,
  },
  miniappPathwayMoveRow: {
    flexDirection: "row",
    gap: spacing.xs,
  },
  miniappPathwayMoveButton: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    minWidth: 78,
  },
  miniappPathwayDangerAction: {
    alignItems: "center",
    backgroundColor: "rgba(248,113,113,0.18)",
    borderColor: "rgba(248,113,113,0.46)",
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 38,
    paddingHorizontal: spacing.md,
    paddingVertical: 9,
  },
  miniappMechanismLegend: {
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  miniappMechanismLegendItem: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.28)",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
  },
  miniappEvidencePanel: {
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  miniappEvidenceItem: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.22)",
    borderRadius: 16,
    borderWidth: 1,
    padding: spacing.sm,
    gap: 2,
  },
  miniappHypothesisCard: {
    backgroundColor: "rgba(255,255,255,0.10)",
    borderColor: "rgba(255,255,255,0.24)",
    borderRadius: 20,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.sm,
  },
  miniappHypothesisStatement: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 13,
    fontWeight: "900",
  },
  miniappExperimentMatrix: {
    gap: spacing.xs,
    padding: spacing.xs,
  },
  miniappExperimentMatrixScroll: {
    maxWidth: "100%",
  },
  miniappExperimentMatrixHeader: {
    ...textClear,
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    minWidth: 92,
  },
  miniappExperimentMatrixCell: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 10,
    minWidth: 90,
  },
  miniappPlannerTimeline: {
    gap: spacing.xs,
  },
  miniappPlannerTimelineItem: {
    backgroundColor: "rgba(255,255,255,0.10)",
    borderColor: "rgba(255,255,255,0.24)",
    borderRadius: 16,
    borderWidth: 1,
    gap: 4,
    padding: spacing.sm,
  },
  miniappDecisionTree: {
    gap: spacing.xs,
    padding: spacing.xs,
  },
  miniappDecisionTreeBranch: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.24)",
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 2,
    padding: spacing.sm,
    gap: 4,
  },
  miniappRiskPanel: {
    gap: spacing.xs,
  },
  miniappRiskChip: {
    backgroundColor: "rgba(255,255,255,0.14)",
    borderColor: "rgba(255,255,255,0.28)",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  miniappRiskChipGood: {
    borderColor: "rgba(34,211,238,0.5)",
    backgroundColor: "rgba(34,211,238,0.14)",
  },
  miniappRiskChipWarning: {
    borderColor: "rgba(251,191,36,0.5)",
    backgroundColor: "rgba(251,191,36,0.14)",
  },
  miniappRiskChipDanger: {
    borderColor: "rgba(248,113,113,0.5)",
    backgroundColor: "rgba(248,113,113,0.14)",
  },
  miniappPlateGridBlock: {
    backgroundColor: "rgba(255,255,255,0.10)",
    borderColor: "rgba(255,255,255,0.24)",
    borderRadius: 24,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  miniappPlateGridScroller: {
    maxWidth: "100%",
  },
  miniappPlateGridContent: {
    gap: 4,
    minWidth: "100%",
  },
  miniappPlateGridRow: {
    flexDirection: "row",
    gap: 4,
  },
  miniappPlateAxisLabel: {
    ...textClear,
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
    width: 20,
  },
  miniappPlateColumnHeader: {
    ...textClear,
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
    width: 24,
  },
  miniappPlateGridCell: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderColor: "rgba(255,255,255,0.2)",
    borderRadius: 4,
    borderWidth: 1,
    height: 22,
    justifyContent: "center",
    width: 24,
  },
  miniappPlateGridCellStandard: {
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  miniappPlateGridCellSample: {
    backgroundColor: "rgba(0, 160, 120, 0.48)",
  },
  miniappPlateGridCellControl: {
    backgroundColor: "rgba(120, 80, 255, 0.48)",
  },
  miniappPlateGridCellEmpty: {
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  miniappPlateGridCellText: {
    ...textClear,
    fontSize: 1,
    opacity: 0,
  },
  miniappSegmentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  miniappSegment: {
    backgroundColor: "rgba(255,255,255,0.24)",
    borderColor: "rgba(255,255,255,0.34)",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
  },
  miniappSegmentActive: {
    backgroundColor: "rgba(255,255,255,0.72)",
    borderColor: "rgba(255,255,255,0.90)",
  },
  miniappSegmentText: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 11,
    fontWeight: "900",
  },
  miniappTabBlock: {
    backgroundColor: "rgba(255,255,255,0.10)",
    borderColor: "rgba(255,255,255,0.24)",
    borderRadius: 24,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  miniappTabPanel: {
    borderColor: "rgba(255,255,255,0.26)",
    borderRadius: 16,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.sm,
  },
  miniappFallbackBlock: {
    backgroundColor: "rgba(255,255,255,0.10)",
    borderColor: "rgba(255,255,255,0.22)",
    borderRadius: 24,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.sm,
  },
  miniappActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  miniappPrimaryAction: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.84)",
    borderColor: "rgba(255,255,255,0.95)",
    borderRadius: 999,
    borderWidth: 1,
    elevation: 4,
    flexDirection: "row",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: 11,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
  },
  miniappPrimaryActionPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.98 }],
  },
  miniappPrimaryActionText: {
    ...textClear,
    color: colors.ink,
    fontSize: 12,
    fontWeight: "900",
  },
  miniappFallbackText: {
    ...textClear,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  askAssistantThinkingText: {
    color: colors.muted,
    fontStyle: "italic",
  },
  askAssistantThinkingRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
  },
  askAssistantGlobeLoader: {
    alignItems: "center",
    backgroundColor: colors.panelBright,
    borderColor: colors.line,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  askAssistantGlobeImage: {
    height: 18,
    width: 18,
  },
  askAssistantQuickRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  askAssistantQuickAction: {
    backgroundColor: colors.panelBright,
    borderColor: colors.line,
    borderRadius: radius.pill,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
  },
  askAssistantQuickText: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 11,
    fontWeight: "800",
  },
  askAssistantInputRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
  },
  askAssistantComposer: {
    backgroundColor: colors.panelBright,
    borderColor: colors.line,
    borderRadius: radius.lg,
    borderWidth: 1,
    padding: spacing.xs,
  },
  askAssistantInput: {
    flex: 1,
    minHeight: 42,
  },
  askAssistantInputPremium: {
    minHeight: 44,
  },
  askAssistantSendButton: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  askAssistantHeaderButton: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderColor: glass.hairline,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    alignSelf: "flex-start",
    flexDirection: "row",
    flexShrink: 0,
    gap: spacing.xs,
    height: 44,
    justifyContent: "center",
    maxWidth: 92,
    minHeight: 44,
    minWidth: 64,
    paddingHorizontal: 8,
    paddingVertical: 0,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 6,
  },
  askAssistantHeaderButtonActive: {
    backgroundColor: colors.danger,
    shadowColor: colors.danger,
  },
  askAssistantHeaderButtonText: {
    ...textClear,
    color: colors.primaryText,
    fontFamily: fontDisplay,
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
    fontWeight: "900",
    textAlign: "center",
  },
  askAssistantHeaderButtonTextActive: {
    color: colors.primaryText,
  },
  page: {
    gap: spacing.md,
  },
  cloudPage: {
    gap: spacing.md,
  },
  labBookShell: {
    flexGrow: 1,
    minHeight: 620,
    paddingBottom: 92,
    position: "relative",
  },
  labBookHero: {
    gap: spacing.sm,
    padding: spacing.md,
  },
  notebookPage: {
    flexGrow: 1,
    minHeight: 620,
    transform: [{ perspective: 900 }],
  },
  notebookContent: {
    flex: 1,
    gap: spacing.md,
    padding: spacing.lg,
  },
  labBookDate: {
    ...textClear,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "900",
  },
  labBookTitleInput: {
    fontSize: 20,
    fontWeight: "900",
  },
  labBookBodyInput: {
    minHeight: 210,
  },
  labBookFooter: {
    gap: spacing.xs,
    paddingRight: 96,
  },
  labBookPhotoPreview: {
    borderRadius: radius.lg,
    height: 150,
    width: "100%",
  },
  labBookAttachmentStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  labBookAttachmentChip: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    maxWidth: "100%",
    minHeight: 34,
    paddingHorizontal: spacing.sm,
  },
  labBookAttachmentText: {
    ...textClear,
    color: colors.ink,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: "800",
  },
  labBookZoomGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  labBookHomeStack: {
    gap: spacing.sm,
    paddingBottom: spacing.xl,
  },
  labBookQuickNoteRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceElev,
    borderWidth: 1,
    borderColor: colors.line,
  },
  labBookQuickNoteIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  labBookQuickNoteTitle: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontBody,
    fontSize: 14,
    fontWeight: "600",
  },
  labBookQuickNoteHint: {
    ...textClear,
    color: colors.muted,
    fontFamily: fontBody,
    fontSize: 12,
    marginTop: 2,
  },
  labBookIndexCard: {
    flexDirection: "row",
    minHeight: 118,
    padding: 0,
    transform: [{ translateY: -1 }],
  },
  labBookIndexTouch: {
    borderRadius: radius.xl,
    flex: 1,
    flexDirection: "row",
    overflow: "hidden",
  },
  labBookIndexBody: {
    flex: 1,
    padding: spacing.sm,
  },
  labBookIndexPhoto: {
    borderRadius: radius.xl,
    height: 74,
    marginLeft: spacing.sm,
    width: 74,
  },
  labBookIndexEmptyPhoto: {
    alignItems: "center",
    backgroundColor: colors.panelBright,
    borderColor: colors.lineStrong,
    borderRadius: radius.xl,
    borderWidth: 1,
    height: 74,
    justifyContent: "center",
    marginLeft: spacing.sm,
    width: 74,
  },
  labBookReaderShell: {
    gap: spacing.md,
    marginHorizontal: -spacing.lg,
  },
  labBookReaderHeader: {
    gap: spacing.sm,
    marginHorizontal: spacing.lg,
    padding: spacing.lg,
  },
  labBookReaderSearchPill: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(20, 184, 166, 0.12)",
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: 34,
    paddingHorizontal: spacing.md,
  },
  labBookReaderSearchText: {
    ...textClear,
    color: colors.ink,
    fontSize: 12,
    fontWeight: "900",
  },
  labBookReaderScroll: {
    flexGrow: 0,
  },
  labBookReaderPageWrap: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  labBookReaderPage: {
    backgroundColor: colors.panelBright,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.xl,
    borderWidth: 1,
    minHeight: 540,
    overflow: "hidden",
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 34 },
    shadowOpacity: 0.28,
    shadowRadius: 54,
    elevation: 14,
  },
  labBookReaderPageContent: {
    flex: 1,
    gap: spacing.md,
    padding: spacing.lg,
  },
  labBookReaderTitle: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 30,
    fontWeight: "800",
    lineHeight: 34,
  },
  labBookReaderExcerpt: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontBody,
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 23,
    opacity: 0.76,
  },
  labBookReaderPhoto: {
    borderRadius: radius.xl,
    flex: 1,
    minHeight: 190,
    width: "100%",
  },
  labBookReaderEmptyPhoto: {
    alignItems: "center",
    backgroundColor: colors.panel,
    borderColor: colors.lineStrong,
    borderRadius: radius.xl,
    borderWidth: 1,
    flex: 1,
    minHeight: 190,
    justifyContent: "center",
  },
  labBookReaderActions: {
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: 150,
    marginHorizontal: spacing.lg,
  },
  labBookMiniPageTouch: {
    borderRadius: radius.lg,
    width: "48%",
  },
  labBookMiniPage: {
    backgroundColor: colors.panelBright,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    gap: spacing.xs,
    minHeight: 232,
    overflow: "hidden",
    padding: spacing.md,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 26 },
    shadowOpacity: 0.24,
    shadowRadius: 38,
    width: "100%",
    elevation: 8,
  },
  labBookMiniDate: {
    ...textClear,
    color: colors.accent,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  labBookMiniTitle: {
    ...textClear,
    color: colors.ink,
    fontSize: 17,
    fontWeight: "900",
  },
  labBookMiniExcerpt: {
    ...textClear,
    color: colors.ink,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
    minHeight: 50,
    opacity: 0.72,
  },
  labBookMiniPhoto: {
    borderRadius: radius.xl,
    height: 72,
    overflow: "hidden",
    width: "100%",
  },
  labBookMiniEmptyPhoto: {
    alignItems: "center",
    backgroundColor: colors.panel,
    borderColor: colors.lineStrong,
    borderRadius: radius.xl,
    borderWidth: 1,
    height: 72,
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    width: "100%",
  },
  labBookMiniFooter: {
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  labBookFab: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderColor: glass.hairline,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    bottom: spacing.lg,
    minHeight: 44,
    minWidth: 44,
    height: 56,
    justifyContent: "center",
    position: "absolute",
    right: spacing.lg,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 22 },
    shadowOpacity: 0.46,
    shadowRadius: 34,
    elevation: 18,
    width: 56,
    zIndex: 8,
  },
  labBookIndexAddButton: {
    alignItems: "center",
    alignSelf: "flex-end",
    backgroundColor: colors.accent,
    borderColor: glass.hairline,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 56,
    justifyContent: "center",
    marginTop: spacing.sm,
    minHeight: 44,
    minWidth: 44,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.34,
    shadowRadius: 24,
    elevation: 12,
    width: 56,
  },
  labBookFanMenu: {
    bottom: 92,
    gap: spacing.sm,
    position: "absolute",
    right: spacing.lg,
    zIndex: 9,
  },
  labBookFanItem: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "flex-end",
  },
  labBookFanLabel: {
    ...textClear,
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 12,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  labBookFanIcon: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    width: 44,
    elevation: 7,
  },
  lockOverlay: {
    alignItems: "center",
    backgroundColor: colors.blackGlass,
    bottom: 0,
    justifyContent: "center",
    left: 0,
    padding: spacing.lg,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 20,
  },
  lockPanel: {
    alignItems: "center",
    gap: spacing.md,
    maxWidth: 360,
    padding: spacing.lg,
    width: "100%",
  },
  glassPanel: {
    backgroundColor: colors.panelSolid,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderLeftColor: glass.hairline,
    borderRadius: radius.xl,
    borderRightColor: colors.lineStrong,
    borderTopColor: glass.hairline,
    borderWidth: 1,
    position: "relative",
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: glass.shadowOpacity,
    shadowRadius: 34,
    elevation: 8,
  },
  glassClip: {
    ...(StyleSheet as any).absoluteFillObject,
    borderRadius: radius.xl,
    overflow: "hidden",
  },
  glassBackdrop: {
    ...(StyleSheet as any).absoluteFillObject,
    borderRadius: radius.xl,
    overflow: "hidden",
  },
  glassTint: {
    ...(StyleSheet as any).absoluteFillObject,
    backgroundColor: colors.panel,
    borderRadius: radius.xl,
  },
  glassSurfaceSheen: {
    backgroundColor: glass.liquidBloom,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    height: 9,
    left: 0,
    opacity: 0.26,
    position: "absolute",
    right: 0,
    top: 0,
  },
  glassSideSheen: {
    backgroundColor: glass.innerGlow,
    bottom: 0,
    left: 0,
    opacity: 0.58,
    position: "absolute",
    top: 0,
    width: 2,
  },
  glassInnerShadow: {
    backgroundColor: glass.innerShadow,
    borderBottomLeftRadius: radius.xl,
    borderBottomRightRadius: radius.xl,
    bottom: 0,
    height: "18%",
    left: 0,
    opacity: 0.30,
    position: "absolute",
    right: 0,
  },
  glassHairline: {
    backgroundColor: glass.hairline,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    height: 2,
    left: 0,
    opacity: 0.82,
    position: "absolute",
    right: 0,
    top: 0,
  },
  glassDepthEdge: {
    backgroundColor: glass.rimDark,
    borderBottomLeftRadius: radius.xl,
    borderBottomRightRadius: radius.xl,
    bottom: 0,
    height: 2,
    left: 0,
    opacity: 0.38,
    position: "absolute",
    right: 0,
  },
  navFrame: {
    backgroundColor: colors.navGlass,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderLeftColor: glass.hairline,
    borderRadius: radius.xl,
    borderRightColor: colors.lineStrong,
    borderTopColor: glass.hairline,
    borderWidth: 1,
    bottom: metrics.bottomNavBottom,
    left: metrics.horizontalPadding,
    overflow: "hidden",
    position: "absolute",
    right: metrics.horizontalPadding,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
    elevation: 10,
    zIndex: 30,
  },
  navBlur: {
    borderRadius: radius.xl,
    overflow: "hidden",
  },
  navLiquidFill: {
    ...(StyleSheet as any).absoluteFillObject,
    backgroundColor: colors.navGlass,
    borderRadius: radius.xl,
  },
  navLiquidRim: {
    backgroundColor: glass.hairline,
    borderRadius: radius.pill,
    height: 2,
    left: 14,
    opacity: 0.9,
    position: "absolute",
    right: 14,
    top: 2,
  },
  bottomNav: {
    backgroundColor: androidGlassSurface,
    borderRadius: radius.xl,
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 5,
  },
  navItem: {
    alignItems: "center",
    borderRadius: radius.pill,
    flexBasis: "19.2%",
    flexGrow: 0,
    flexShrink: 0,
    gap: 2,
    minHeight: 50,
    minWidth: 0,
    justifyContent: "center",
  },
  navItemActive: {
    backgroundColor: colors.panelBright,
    borderColor: glass.hairline,
    borderTopColor: glass.hairline,
    borderWidth: 1,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
    transform: [{ translateY: -1 }],
    elevation: 5,
  },
  navText: {
    ...textClear,
    color: colors.muted,
    fontFamily: fontDisplay,
    fontSize: 10,
    fontWeight: "800",
  },
  navTextActive: {
    color: colors.ink,
  },
  heroPanel: {
    padding: spacing.md,
  },
  kicker: {
    ...textClear,
    color: colors.accent,
    fontFamily: fontDisplay,
    fontSize: 11,
    fontWeight: "800",
    marginBottom: spacing.xs,
    textTransform: "uppercase",
  },
  heroTitle: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: 0,
  },
  heroTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  heroTitleText: {
    flex: 1,
  },
  heroBody: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontBody,
    fontSize: 13,
    lineHeight: 19,
    marginTop: spacing.sm,
  },
  heroMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  glassPill: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderTopColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    overflow: "hidden",
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 1,
  },
  glassPillText: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 11,
    fontWeight: "900",
  },
  section: {
    gap: spacing.sm,
  },
  sectionTitle: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 16,
    fontWeight: "800",
  },
  organismGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  organismCard: {
    backgroundColor: colors.panelSoft,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    minHeight: 118,
    padding: spacing.md,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    width: "48%",
    elevation: 0,
  },
  organismAccent: {
    borderRadius: radius.pill,
    height: 4,
    marginBottom: spacing.md,
    width: 34,
  },
  cardTitle: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 16,
    fontWeight: "800",
  },
  cardMeta: {
    ...textClear,
    color: colors.muted,
    fontFamily: fontBody,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  cardSmall: {
    ...textClear,
    color: colors.muted,
    fontFamily: fontBody,
    fontSize: 13,
    lineHeight: 18,
    marginTop: spacing.xs,
  },
  inputShell: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderLeftColor: glass.hairline,
    borderRadius: radius.lg,
    borderRightColor: colors.lineStrong,
    borderTopColor: glass.hairline,
    borderWidth: 1,
    minHeight: 50,
    position: "relative",
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.10,
    shadowRadius: 20,
    elevation: 5,
  },
  inputClip: {
    ...(StyleSheet as any).absoluteFillObject,
    borderRadius: radius.lg,
    overflow: "hidden",
  },
  inputBackdrop: {
    ...(StyleSheet as any).absoluteFillObject,
    borderRadius: radius.lg,
    overflow: "hidden",
  },
  inputTint: {
    ...(StyleSheet as any).absoluteFillObject,
    backgroundColor: colors.inputNativeFill,
    borderRadius: radius.lg,
  },
  inputHairline: {
    backgroundColor: glass.hairline,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    height: 2,
    left: 0,
    opacity: 0.88,
    position: "absolute",
    right: 0,
    top: 0,
  },
  input: {
    ...textClear,
    backgroundColor: "transparent",
    borderRadius: radius.lg,
    borderWidth: 0,
    color: colors.ink,
    fontFamily: fontBody,
    fontSize: 15,
    minHeight: 50,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  intentInput: {
    minHeight: 118,
  },
  qpcrCsvInput: {
    minHeight: 126,
  },
  qpcrCommandPanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  qpcrRunPanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  qpcrCommandTop: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  qpcrCommandIcon: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderColor: "rgba(232, 238, 231, 0.46)",
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.30,
    shadowRadius: 18,
    width: 48,
    elevation: 8,
  },
  qpcrMetricStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  qpcrMetricPill: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexGrow: 1,
    minHeight: 54,
    minWidth: 92,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  qpcrMetricValue: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 15,
    fontWeight: "900",
  },
  qpcrMetricLabel: {
    ...textClear,
    color: colors.quiet,
    fontFamily: fontDisplay,
    fontSize: 10,
    fontWeight: "900",
    marginTop: 2,
    textTransform: "uppercase",
  },
  qpcrSetupPanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  qpcrSetupGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  qpcrSetupField: {
    flexBasis: 160,
    flexGrow: 1,
    gap: spacing.xs,
  },
  qpcrQuickPickGrid: {
    gap: spacing.sm,
  },
  qpcrQuickPickBlock: {
    gap: spacing.xs,
  },
  qpcrQuickPickRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  qpcrQuickPickChip: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  qpcrQuickPickChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 5,
  },
  qpcrQuickPickText: {
    ...textClear,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "900",
  },
  qpcrQuickPickTextActive: {
    color: colors.primaryText,
  },
  columnMapPanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  columnChipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  columnChip: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.lg,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  columnChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
    borderTopColor: glass.hairline,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.20,
    shadowRadius: 12,
    elevation: 4,
  },
  columnChipText: {
    ...textClear,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "900",
  },
  columnChipTextActive: {
    color: colors.primaryText,
  },
  checkRow: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 64,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  checkbox: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.lineStrong,
    borderRadius: radius.sm,
    borderWidth: 1,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  checkboxActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  guardrailPanel: {
    gap: spacing.xs,
    padding: spacing.md,
  },
  issueText: {
    color: colors.amber,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
  },
  previewPanel: {
    gap: spacing.md,
    padding: spacing.lg,
  },
  qpcrPreviewPanel: {
    gap: spacing.xs,
    padding: spacing.md,
  },
  qpcrPreviewToggle: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 58,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  qpcrExportPanel: {
    padding: spacing.md,
  },
  qpcrResultSheet: {
    gap: spacing.md,
    padding: spacing.lg,
  },
  qpcrSavedRow: {
    padding: spacing.md,
  },
  previewText: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 22,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderColor: "rgba(232, 238, 231, 0.46)",
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: 50,
    justifyContent: "center",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.34,
    shadowRadius: 22,
    elevation: 10,
  },
  computePrimaryButton: {
    backgroundColor: colors.compute,
    shadowColor: colors.compute,
  },
  primaryButtonText: {
    color: colors.primaryText,
    fontSize: 15,
    fontWeight: "900",
  },
  statusPanel: {
    gap: spacing.md,
    padding: spacing.lg,
  },
  rowBetween: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: spacing.md,
    justifyContent: "space-between",
  },
  flexOne: {
    flex: 1,
  },
  statusBadge: {
    borderRadius: radius.md,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  statusBadgeText: {
    ...textClear,
    fontSize: 11,
    fontWeight: "900",
  },
  jobCard: {
    gap: spacing.md,
    padding: spacing.md,
  },
  rnaAnalysisHeroCard: {
    gap: spacing.md,
    padding: spacing.lg,
  },
  rnaAnalysisTitle: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 24,
    fontWeight: "900",
  },
  rnaAnalysisBody: {
    ...textClear,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 19,
  },
  rnaAnalysisOrb: {
    alignItems: "center",
    backgroundColor: colors.compute,
    borderColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    shadowColor: colors.compute,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    width: 48,
    elevation: 8,
  },
  rnaAnalysisStats: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  rnaAnalysisStat: {
    backgroundColor: colors.panelSoft,
    borderColor: colors.line,
    borderRadius: radius.md,
    borderWidth: 1,
    flex: 1,
    minWidth: 74,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  rnaAnalysisStatValue: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 18,
    fontWeight: "900",
  },
  rnaAnalysisStatLabel: {
    ...textClear,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  rnaActionGrid: {
    gap: spacing.sm,
  },
  rnaActionCard: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 76,
    padding: spacing.md,
  },
  rnaActionCardPrimary: {
    borderColor: colors.lineStrong,
    backgroundColor: colors.panelSoft,
  },
  rnaActionIcon: {
    alignItems: "center",
    backgroundColor: colors.panelSoft,
    borderColor: colors.line,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  rnaActionTitle: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 15,
    fontWeight: "900",
  },
  rnaActionBody: {
    ...textClear,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  rnaActionCount: {
    ...textClear,
    color: colors.accent,
    fontFamily: fontDisplay,
    fontSize: 18,
    fontWeight: "900",
    minWidth: 24,
    textAlign: "right",
  },
  analysisGroup: {
    gap: spacing.sm,
  },
  analysisDate: {
    ...textClear,
    color: colors.quiet,
    fontSize: 12,
    fontWeight: "900",
    marginTop: spacing.xs,
  },
  analysisCard: {
    gap: spacing.md,
    padding: spacing.md,
  },
  analysisCardActive: {
    borderColor: colors.lineStrong,
    backgroundColor: androidGlassSurface,
  },
  selectedAnalysisPanel: {
    gap: spacing.xs,
    padding: spacing.lg,
  },
  textButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    flexDirection: "row",
    gap: spacing.xs,
    marginTop: spacing.sm,
    minHeight: 44,
  },
  textButtonText: {
    fontSize: 13,
    fontWeight: "900",
  },
  deletePanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  analysisTabs: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  analysisTabButton: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  analysisTabButtonActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  analysisTabText: {
    ...textClear,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "900",
  },
  analysisTabTextActive: {
    color: colors.primaryText,
  },
  segmentDisabled: {
    opacity: 0.45,
  },
  guideIntroPanel: {
    gap: spacing.xs,
    padding: spacing.md,
  },
  guideSlidePanel: {
    gap: spacing.sm,
    padding: spacing.md,
  },
  guideCheckRow: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  privacyBadge: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: androidGlassSurface,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.xs,
    maxWidth: "100%",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  privacyBadgeLabel: {
    ...textClear,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  rnaSamplesheetPanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  disclosureCardStack: {
    gap: spacing.sm,
  },
  disclosureCard: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: "hidden",
  },
  disclosureCardError: {
    borderColor: colors.danger,
  },
  disclosureCardWarning: {
    borderColor: colors.amber,
  },
  disclosureCardTrigger: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 44,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  disclosureCardIcon: {
    alignItems: "center",
    backgroundColor: colors.panelSoft,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  disclosureCardCopy: {
    flex: 1,
    minWidth: 0,
  },
  disclosureCardTitle: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 13,
    fontWeight: "900",
  },
  disclosureCardSummary: {
    ...textClear,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  disclosureCardBody: {
    borderTopColor: colors.line,
    borderTopWidth: 1,
    gap: spacing.sm,
    padding: spacing.md,
  },
  rnaSourceStatusStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  rnaSourceStatusPill: {
    backgroundColor: colors.panelSoft,
    borderColor: colors.line,
    borderRadius: radius.pill,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  rnaSourceStatusPillActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  rnaSourceStatusText: {
    ...textClear,
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  rnaSourceStatusTextActive: {
    color: colors.primaryText,
  },
  rnaCompactSummary: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  rnaCompactStat: {
    backgroundColor: colors.panelSoft,
    borderColor: colors.line,
    borderRadius: radius.md,
    borderWidth: 1,
    minWidth: 74,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  rnaCompactStatValue: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 15,
    fontWeight: "900",
  },
  rnaCompactStatLabel: {
    ...textClear,
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  rnaSubmitReviewHero: {
    borderRadius: radius.lg,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.md,
  },
  rnaSubmitReviewHeroReady: {
    backgroundColor: "rgba(43,111,87,0.14)",
    borderColor: colors.accent,
  },
  rnaSubmitReviewHeroBlocked: {
    backgroundColor: "rgba(182,122,45,0.14)",
    borderColor: colors.amber,
  },
  rnaSubmitReviewTitle: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 16,
    fontWeight: "900",
  },
  rnaSubmitReviewBody: {
    ...textClear,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  rnaWizardRail: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.xl,
    borderWidth: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    padding: spacing.xs,
  },
  rnaWizardStep: {
    alignItems: "center",
    backgroundColor: colors.panelSoft,
    borderColor: colors.line,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexBasis: "31.8%",
    flexDirection: "row",
    flexGrow: 1,
    gap: spacing.xs,
    minHeight: 46,
    minWidth: 96,
    paddingHorizontal: spacing.xs,
  },
  rnaWizardStepActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.20,
    shadowRadius: 14,
    elevation: 5,
  },
  rnaWizardStepIndex: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  rnaWizardStepIndexActive: {
    backgroundColor: "rgba(232,238,231,0.30)",
    borderColor: glass.hairline,
  },
  rnaWizardStepIndexDone: {
    backgroundColor: colors.compute,
    borderColor: colors.compute,
  },
  rnaWizardStepIndexText: {
    ...textClear,
    color: colors.muted,
    fontFamily: fontDisplay,
    fontSize: 11,
    fontWeight: "900",
  },
  rnaWizardStepIndexTextActive: {
    color: colors.primaryText,
  },
  rnaWizardStepLabel: {
    ...textClear,
    color: colors.ink,
    flexShrink: 1,
    fontFamily: fontDisplay,
    fontSize: 12,
    fontWeight: "900",
  },
  rnaWizardStepLabelActive: {
    color: colors.primaryText,
  },
  rnaCoachPanel: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: spacing.sm,
    padding: spacing.md,
  },
  rnaCoachIcon: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    width: 36,
    elevation: 5,
  },
  rnaCoachCopy: {
    flex: 1,
    minWidth: 0,
  },
  rnaCoachAskButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: colors.accent,
    borderColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: 40,
    marginTop: spacing.sm,
    paddingHorizontal: spacing.md,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
    elevation: 4,
  },
  rnaCoachAskButtonText: {
    ...textClear,
    color: colors.primaryText,
    fontFamily: fontDisplay,
    fontSize: 12,
    fontWeight: "900",
  },
  rnaSampleRow: {
    alignItems: "stretch",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  rnaSampleRowHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
  },
  rnaSampleIndexBadge: {
    alignItems: "center",
    backgroundColor: colors.panelSoft,
    borderColor: colors.line,
    borderRadius: radius.md,
    borderWidth: 1,
    minHeight: 32,
    justifyContent: "center",
    width: 38,
  },
  rnaSampleIndexText: {
    ...textClear,
    color: colors.muted,
    fontFamily: fontDisplay,
    fontSize: 11,
    fontWeight: "900",
  },
  rnaSampleRowActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
  },
  rnaSampleStatusBadge: {
    alignItems: "center",
    backgroundColor: colors.panelSoft,
    borderColor: colors.amber,
    borderRadius: radius.pill,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 32,
    paddingHorizontal: spacing.sm,
  },
  rnaSampleStatusBadgeReady: {
    borderColor: colors.accent,
  },
  rnaSampleStatusText: {
    ...textClear,
    color: colors.amber,
    fontFamily: fontDisplay,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  rnaSampleStatusTextReady: {
    color: colors.accent,
  },
  rnaSampleFields: {
    gap: spacing.xs,
  },
  rnaSampleInput: {
    minHeight: 44,
  },
  rnaSamplesheetAddRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  rnaConditionQuickRow: {
    flexDirection: "row",
    gap: spacing.xs,
  },
  rnaConditionChip: {
    alignItems: "center",
    backgroundColor: colors.panelSoft,
    borderColor: colors.line,
    borderRadius: radius.md,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: spacing.sm,
  },
  rnaConditionChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  rnaConditionChipText: {
    ...textClear,
    color: colors.muted,
    fontFamily: fontDisplay,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  rnaConditionChipTextActive: {
    color: colors.primaryText,
  },
  rnaStepFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  rnaStepFooterLabel: {
    ...textClear,
    color: colors.muted,
    flex: 1,
    fontFamily: fontDisplay,
    fontSize: 11,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  qcBadge: {
    borderRadius: radius.md,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  qcBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  progressTrack: {
    backgroundColor: colors.progressTrack,
    borderRadius: radius.pill,
    height: 10,
    overflow: "hidden",
  },
  progressFill: {
    borderRadius: radius.pill,
    height: 10,
  },
  qpcrResultRow: {
    gap: spacing.md,
    padding: spacing.md,
  },
  qpcrTargetPanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  qpcrGroupGrid: {
    gap: spacing.sm,
  },
  qpcrGroupBlock: {
    borderColor: colors.line,
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    gap: spacing.sm,
    padding: spacing.md,
  },
  qpcrBarTrack: {
    backgroundColor: colors.progressTrack,
    borderRadius: radius.pill,
    height: 10,
    overflow: "hidden",
  },
  qpcrBarFill: {
    backgroundColor: colors.accent,
    borderRadius: radius.pill,
    height: 10,
  },
  qpcrDotTrack: {
    backgroundColor: colors.progressTrack,
    borderRadius: radius.md,
    height: 36,
    overflow: "hidden",
    position: "relative",
  },
  qpcrDot: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderRadius: radius.pill,
    height: 22,
    justifyContent: "center",
    minWidth: 22,
    paddingHorizontal: 5,
    position: "absolute",
    top: 7,
  },
  qpcrDotText: {
    color: colors.primaryText,
    fontSize: 10,
    fontWeight: "900",
  },
  qpcrGraphPadPanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  timeline: {
    padding: spacing.md,
  },
  timelineRow: {
    flexDirection: "row",
    minHeight: 58,
  },
  timelineRail: {
    alignItems: "center",
    width: 28,
  },
  timelineDot: {
    borderRadius: radius.pill,
    height: 12,
    marginTop: 4,
    width: 12,
  },
  timelineLine: {
    backgroundColor: colors.lineStrong,
    flex: 1,
    marginTop: spacing.xs,
    width: 1,
  },
  timelineContent: {
    flex: 1,
    paddingBottom: spacing.md,
  },
  rnaLivePanel: {
    backgroundColor: colors.panelSoft,
    borderColor: colors.line,
    borderRadius: radius.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  rnaLiveHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  rnaLiveIcon: {
    alignItems: "center",
    borderColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 16,
    width: 44,
    elevation: 5,
  },
  rnaLiveFlow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  rnaLiveStepChip: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderRadius: radius.pill,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    minHeight: 32,
    paddingHorizontal: spacing.xs,
  },
  rnaLiveStepChipActive: {
    backgroundColor: colors.panelBright,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.10,
    shadowRadius: 12,
    elevation: 3,
  },
  rnaLiveStepIndex: {
    ...textClear,
    fontFamily: fontDisplay,
    fontSize: 10,
    fontWeight: "900",
  },
  rnaLiveStepText: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 11,
    fontWeight: "900",
    maxWidth: 58,
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  metricCard: {
    flex: 1,
    minHeight: 88,
    minWidth: 134,
    padding: spacing.md,
  },
  metricValue: {
    ...textClear,
    fontFamily: fontDisplay,
    fontSize: 23,
    fontWeight: "800",
    marginTop: spacing.xs,
  },
  textPanel: {
    padding: spacing.md,
  },
  privacyPanel: {
    gap: spacing.sm,
    padding: spacing.md,
  },
  toolHeroPanel: {
    gap: spacing.md,
    padding: spacing.lg,
  },
  toolHeroTop: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: spacing.md,
  },
  toolHeroIcon: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderColor: "rgba(232, 238, 231, 0.46)",
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    height: 52,
    justifyContent: "center",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.34,
    shadowRadius: 22,
    width: 52,
    elevation: 9,
  },
  toolHeroTitle: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: 0,
  },
  toolHeroBody: {
    ...textClear,
    color: colors.muted,
    fontFamily: fontBody,
    fontSize: 13,
    lineHeight: 19,
    marginTop: spacing.xs,
  },
  toolStatGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  toolStatChip: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.md,
    borderWidth: 1,
    flexGrow: 1,
    minHeight: 58,
    minWidth: 132,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.09,
    shadowRadius: 15,
    width: "48%",
    elevation: 0,
  },
  toolStatValue: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 17,
    fontWeight: "800",
  },
  toolStatLabel: {
    ...textClear,
    color: colors.quiet,
    fontFamily: fontDisplay,
    fontSize: 10,
    fontWeight: "900",
    marginTop: 3,
    textTransform: "uppercase",
  },
  photoSourcePanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  photoIconBadge: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderRadius: radius.md,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  photoNotesInput: {
    minHeight: 120,
  },
  photoResultPanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  photoMiniGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  photoMiniStat: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.md,
    borderWidth: 1,
    flexGrow: 1,
    minHeight: 58,
    minWidth: 126,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    width: "31%",
  },
  benchToolbarPanel: {
    gap: spacing.sm,
    padding: spacing.md,
  },
  benchToolbarTitle: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: 0,
  },
  benchToolbarMeta: {
    ...textClear,
    color: colors.muted,
    fontFamily: fontBody,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
    marginTop: 2,
  },
  benchToolRail: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    padding: 5,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.10,
    shadowRadius: 18,
    elevation: 3,
  },
  benchToolPill: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderRadius: radius.pill,
    borderWidth: 0,
    flex: 1,
    flexDirection: "column",
    gap: 3,
    justifyContent: "center",
    minHeight: 50,
    paddingHorizontal: 2,
  },
  benchToolPillActive: {
    backgroundColor: colors.accent,
    borderColor: "rgba(232,238,231,0.46)",
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderWidth: 1,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 14,
    elevation: 6,
  },
  benchToolGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  benchToolCard: {
    alignItems: "center",
    backgroundColor: colors.panelSoft,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 68,
    minWidth: 154,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    width: "48%",
    elevation: 0,
  },
  benchToolCardActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
    borderTopColor: glass.hairline,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    transform: [{ translateY: -1 }],
    elevation: 7,
  },
  benchToolIcon: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  benchToolIconActive: {
    backgroundColor: "rgba(232,238,231,0.28)",
  },
  benchToolTitle: {
    ...textClear,
    color: colors.ink,
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  benchToolTitleActive: {
    color: colors.primaryText,
  },
  benchToolMeta: {
    ...textClear,
    color: colors.muted,
    flexShrink: 1,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
    marginTop: 2,
  },
  benchToolMetaActive: {
    color: colors.primaryText,
  },
  benchToolStack: {
    gap: spacing.md,
  },
  benchCalcHero: {
    padding: spacing.md,
  },
  benchCardGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  benchCalcCard: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.lineStrong,
    gap: spacing.sm,
    minHeight: 174,
    padding: spacing.md,
    width: "100%",
  },
  benchCalcInputStack: {
    gap: spacing.sm,
  },
  benchCalcFieldGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  benchCalcField: {
    flexBasis: 92,
    flexGrow: 1,
    gap: 4,
    position: "relative",
  },
  benchCalcFullInput: {
    gap: 4,
    width: "100%",
  },
  benchCalcInputLabel: {
    ...textClear,
    color: colors.quiet,
    fontFamily: fontDisplay,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  benchCalcInput: {
    minHeight: 42,
  },
  benchCalcTextArea: {
    minHeight: 86,
  },
  benchCalcInputSuffix: {
    ...textClear,
    bottom: 12,
    color: colors.quiet,
    fontSize: 10,
    fontWeight: "900",
    position: "absolute",
    right: spacing.sm,
  },
  plateTypeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  plateTypeChip: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  plateTypeChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 5,
  },
  plateTypeChipText: {
    ...textClear,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "900",
  },
  plateTypeChipTextActive: {
    color: colors.primaryText,
  },
  plateStatusPanel: {
    padding: spacing.md,
  },
  platePreviewPanel: {
    gap: spacing.sm,
    padding: spacing.md,
  },
  plateGridRow: {
    flexDirection: "row",
    gap: 4,
    marginBottom: 4,
  },
  plateAxisCell: {
    ...textClear,
    color: colors.quiet,
    fontSize: 10,
    fontWeight: "900",
    height: 34,
    lineHeight: 34,
    textAlign: "center",
    width: 44,
  },
  plateAxisCellDense: {
    width: 34,
  },
  plateWellCell: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.sm,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    paddingHorizontal: 2,
    width: 44,
  },
  plateWellCellDense: {
    height: 34,
    width: 34,
  },
  plateWellCellFilled: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  plateWellText: {
    ...textClear,
    color: colors.quiet,
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  benchCalcIcon: {
    alignItems: "center",
    borderRadius: radius.md,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  benchCalcIcon_aqueous: {
    backgroundColor: "#3BA4F4",
  },
  benchCalcIcon_sample: {
    backgroundColor: "#79F2C0",
  },
  benchCalcIcon_mix: {
    backgroundColor: "#B18CFF",
  },
  benchCalcIcon_clone: {
    backgroundColor: "#F9C784",
  },
  benchCalcIcon_dna: {
    backgroundColor: "#5DD7C7",
  },
  benchCalcIcon_buffer: {
    backgroundColor: "#B6A16B",
  },
  benchCalcIcon_cells: {
    backgroundColor: "#F28B82",
  },
  benchCalcIcon_plate: {
    backgroundColor: "#8DD8FF",
  },
  benchCalcPrimary: {
    ...textClear,
    color: colors.ink,
    fontSize: 22,
    fontWeight: "900",
  },
  benchCalcRow: {
    borderTopColor: colors.line,
    borderTopWidth: 1,
    gap: 2,
    paddingTop: spacing.xs,
  },
  benchCalcValue: {
    ...textClear,
    color: colors.ink,
    fontSize: 14,
    fontWeight: "900",
  },
  dnaInput: {
    minHeight: 180,
  },
  dnaResultPanel: {
    gap: spacing.sm,
    padding: spacing.md,
  },
  dnaListRow: {
    padding: spacing.md,
  },
  monoText: {
    ...textClear,
    color: colors.ink,
    fontSize: 12,
    lineHeight: 18,
  },
  monoBadge: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.pill,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 38,
    overflow: "hidden",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  monoBadgeText: {
    ...textClear,
    color: colors.ink,
    fontSize: 11,
    fontWeight: "900",
  },
  authPanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  usagePanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  usageGrid: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  usageStat: {
    flex: 1,
    minHeight: 78,
  },
  askAiUsagePanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  askAiUsageHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
  },
  askAiUsageGaugeGrid: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  askAiUsageGauge: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    gap: spacing.xs,
    minHeight: 132,
    padding: spacing.sm,
  },
  askAiUsagePie: {
    alignItems: "center",
    backgroundColor: colors.progressTrack,
    borderColor: colors.line,
    borderRadius: 36,
    borderWidth: 1,
    height: 72,
    justifyContent: "center",
    overflow: "hidden",
    position: "relative",
    width: 72,
  },
  askAiUsagePieFill: {
    bottom: 0,
    left: 0,
    opacity: 0.86,
    position: "absolute",
    right: 0,
  },
  askAiUsagePieCenter: {
    alignItems: "center",
    backgroundColor: colors.panelSolid,
    borderColor: colors.line,
    borderRadius: 24,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  askAiUsagePieValue: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 12,
    fontWeight: "900",
  },
  askAiUsageBudgetLine: {
    alignItems: "center",
    borderTopColor: colors.line,
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: spacing.sm,
  },
  plotPreview: {
    alignItems: "center",
    gap: spacing.sm,
    minHeight: 150,
    justifyContent: "center",
    padding: spacing.lg,
  },
  plotCanvas: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.lg,
    borderWidth: 1,
    gap: spacing.sm,
    minHeight: 120,
    justifyContent: "center",
    width: "100%",
  },
  viewerPanel: {
    gap: spacing.md,
    padding: spacing.md,
  },
  webView: {
    backgroundColor: "transparent",
    borderRadius: radius.md,
    height: 220,
    overflow: "hidden",
  },
  csvRow: {
    flexDirection: "row",
    gap: 4,
  },
  csvCell: {
    ...textClear,
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderRadius: radius.sm,
    borderWidth: 1,
    color: colors.muted,
    fontFamily: fontBody,
    flex: 1,
    fontSize: 11,
    fontWeight: "700",
    minHeight: 30,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  csvHeader: {
    color: colors.ink,
    fontWeight: "900",
  },
  bodyText: {
    ...textClear,
    color: colors.muted,
    fontFamily: fontBody,
    fontSize: 14,
    lineHeight: 21,
  },
  fileRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
    justifyContent: "space-between",
    minHeight: 68,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  fileName: {
    ...textClear,
    color: colors.ink,
    fontFamily: fontDisplay,
    fontSize: 14,
    fontWeight: "800",
  },
  openButton: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderWidth: 1,
    borderRadius: radius.pill,
    height: 44,
    justifyContent: "center",
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    width: 44,
    elevation: 3,
  },
  accountHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
    padding: spacing.lg,
  },
  accountSectionHeader: {
    padding: spacing.md,
  },
  themeSwitcher: {
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    padding: 6,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 5,
  },
  themeOption: {
    alignItems: "center",
    borderRadius: radius.lg,
    flex: 1,
    flexDirection: "row",
    gap: spacing.xs,
    justifyContent: "center",
    minHeight: 44,
  },
  themeOptionActive: {
    backgroundColor: colors.accent,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.26,
    shadowRadius: 14,
    elevation: 6,
  },
  themeOptionText: {
    ...textClear,
    color: colors.muted,
    fontFamily: fontDisplay,
    fontSize: 13,
    fontWeight: "900",
  },
  themeOptionTextActive: {
    color: colors.primaryText,
  },
  inlineActions: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  primaryMiniButton: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderColor: "rgba(232, 238, 231, 0.46)",
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: 44,
    paddingHorizontal: spacing.md,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.30,
    shadowRadius: 18,
    elevation: 8,
  },
  primaryMiniButtonDisabled: {
    opacity: 0.42,
  },
  primaryMiniButtonText: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 13,
    fontWeight: "900",
  },
  secondaryMiniButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: spacing.md,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.10,
    shadowRadius: 16,
    elevation: 4,
  },
  secondaryMiniButtonText: {
    ...textClear,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "900",
  },
  disabledMiniButton: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.line,
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: 44,
    opacity: 0.58,
    paddingHorizontal: spacing.md,
  },
  disabledMiniButtonText: {
    ...textClear,
    color: colors.quiet,
    fontSize: 13,
    fontWeight: "900",
  },
  dangerButton: {
    alignItems: "center",
    backgroundColor: colors.danger,
    borderColor: "rgba(232, 238, 231, 0.42)",
    borderBottomColor: glass.rimDark,
    borderTopColor: glass.hairline,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: 38,
    paddingHorizontal: spacing.md,
    shadowColor: colors.danger,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.26,
    shadowRadius: 18,
    elevation: 7,
  },
  dangerButtonText: {
    ...textClear,
    color: colors.primaryText,
    fontSize: 13,
    fontWeight: "900",
  },
  avatar: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderColor: colors.lineStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 50,
    justifyContent: "center",
    width: 50,
  },
  settingRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 72,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  settingIcon: {
    alignItems: "center",
    backgroundColor: androidGlassSurface,
    borderRadius: radius.pill,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  readinessPanel: {
    gap: spacing.sm,
    padding: spacing.md,
  },
  readinessRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
  },
  });
}
