#!/usr/bin/env bash
# Every local #include in the assembled engine must resolve to a file on disk.
#
# The engine is installed from the fork Aspis0/kalsa.rn. It used to be a
# FLATTENING of kalsallama through an explicit allow-list that did not learn:
# upstream added a file, a source started including it, the header was simply
# absent, and the NDK failed ~5 minutes into the APK build, far from the cause.
# That is how
#   common/peg-parser.h:3:10: fatal error: 'json.h' file not found
# reached CI on 2026-09-17.
#
# That allow-list is gone: the fork now vendors whole directories into
# vendor/llama.cpp (scripts/sync-vendor.sh, rsync -a --delete), so a file
# upstream adds inside an exported directory arrives on its own and the
# original failure mode is structurally impossible. The gate is kept for the
# two things that layout does NOT make impossible: a directory the vendor
# manifest never names at all, and the API drift phase two catches, which
# never depended on how the tree was assembled.
#
# This gate runs in seconds and fails at the point of assembly instead.
# Conditional backend includes (CUDA, Vulkan, …) and build-generated headers
# are listed as known-absent; anything else is a missing vendor file.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CPP="$ROOT/node_modules/llama.rn/cpp"
VENDOR="$ROOT/node_modules/llama.rn/vendor/llama.cpp"
CODEC="$ROOT/node_modules/llama.rn/vendor/codec.cpp"
[ -d "$CPP" ] || { echo "[includes] missing $CPP — run npm install" >&2; exit 1; }
# Before the vendor migration the engine lived in cpp/ itself. A pin from
# before it has no vendor/llama.cpp and every count below would be zero --
# which this gate must name, not report as an empty pass.
[ -d "$VENDOR" ] || {
  echo "[includes] missing $VENDOR" >&2
  echo "[includes] the installed llama.rn predates the vendor migration; bump the pin" >&2
  exit 1
}

# The build does not compile every file it vendors: rnllama-sources.cmake
# filters nine sources out of common/ (llguidance.cpp needs an external crate
# header that is deliberately absent). Scanning or parsing them reports a dead
# file as a defect. Read the exclusion out of the installed cmake instead of
# copying the names here -- a second hand-written list is the thing that
# drifts, and this one already would have.
SOURCES_CMAKE="$ROOT/node_modules/llama.rn/cmake/rnllama-sources.cmake"
[ -f "$SOURCES_CMAKE" ] || { echo "[includes] missing $SOURCES_CMAKE" >&2; exit 1; }
EXCLUDED="$(python3 - "$SOURCES_CMAKE" <<'EX'
import re, sys
body = open(sys.argv[1]).read()
m = re.search(r'RNLLAMA_COMMON_SOURCES EXCLUDE REGEX\s*\n?\s*"/\(([^)]*)\)', body)
if not m:
    sys.exit("[includes] cannot read the common/ exclusion from rnllama-sources.cmake")
print(" ".join(n + ".cpp" for n in m.group(1).split("|")))
EX
)"
[ -n "$EXCLUDED" ] || { echo "[includes] empty exclusion list -- refusing to guess" >&2; exit 1; }
echo "[includes] build excludes from common/: $EXCLUDED"

python3 - "$CPP" "$VENDOR" "$EXCLUDED" <<'PY'
import os, re, sys, glob

cpp, vendor = sys.argv[1], sys.argv[2]
EXCLUDED = set(sys.argv[3].split())

# Guarded by #ifdef for a backend we never build, or emitted by the build.
KNOWN_ABSENT = {
    "ggml-cann.h", "ggml-cuda.h", "ggml-et.h", "ggml-openvino.h", "ggml-rpc.h",
    "ggml-sycl.h", "ggml-virtgpu.h", "ggml-vulkan.h", "ggml-webgpu.h",
    "ggml-zdnn.h", "ggml-zendnn.h",
    "llama-version.h",          # generated by the build
    "sheredom/subprocess.h",    # mtmd-helper.cpp, behind #ifdef MTMD_VIDEO
}
# Where a quoted include may resolve. Mirrors RNLLAMA_INCLUDE_DIRS in the
# fork's cmake/rnllama-sources.cmake: a search path this gate has and the
# build does not would let it pass an engine the NDK cannot compile.
SEARCH = [
    cpp,
    vendor,                                       # "tools/mtmd/mtmd.h"-style
    os.path.join(vendor, "include"),
    os.path.join(vendor, "src"),
    os.path.join(vendor, "common"),
    os.path.join(vendor, "ggml", "include"),
    os.path.join(vendor, "ggml", "src"),
    os.path.join(vendor, "ggml", "src", "ggml-cpu"),
    os.path.join(vendor, "tools", "mtmd"),
    os.path.join(vendor, "vendor"),
    os.path.join(vendor, "vendor", "hash"),
    os.path.join(os.path.dirname(vendor), "codec.cpp", "include"),
    os.path.join(os.path.dirname(vendor), "codec.cpp", "common"),
]

# The binding lives in cpp/, the engine in vendor/llama.cpp/. Both are scanned:
# the drift this gate exists for happens where they meet.
files = []
for root, pats in (
    (cpp,    ("*.h", "*.cpp", "jsi/*.h", "jsi/*.cpp")),
    (vendor, ("common/*.h", "common/*.cpp",
              "common/jinja/*.h", "common/jinja/*.cpp",
              "tools/mtmd/*.h", "tools/mtmd/*.cpp")),
):
    for pat in pats:
        files += [f for f in glob.glob(os.path.join(root, pat))
                  if os.path.basename(f) not in EXCLUDED]
if not files:
    print("[includes] FAIL: scanned zero files -- the installed layout is not what this gate expects")
    raise SystemExit(1)

missing = {}
for f in files:
    with open(f, errors="ignore") as fh:
        body = fh.read()
    for m in re.finditer(r'^\s*#\s*include\s+"([^"]+)"', body, re.M):
        inc = m.group(1)
        if inc in KNOWN_ABSENT:
            continue
        here = os.path.join(os.path.dirname(f), inc)
        if os.path.exists(here) or any(os.path.exists(os.path.join(d, inc)) for d in SEARCH):
            continue
        missing.setdefault(inc, []).append(os.path.relpath(f, os.path.dirname(cpp)))

if missing:
    print(f"[includes] FAIL: {len(missing)} unresolved include(s) in the assembled engine")
    for inc, users in sorted(missing.items()):
        print(f"  {inc}  <- {', '.join(sorted(users)[:4])}")
    print("[includes] in the fork: the vendor manifest in scripts/sync-vendor.sh does not")
    print("[includes] reach this file. Add its directory there, re-run `npm run sync:vendor`,")
    print("[includes] push, then move the app to the new fork sha and `npm install`.")
    raise SystemExit(1)

print(f"[includes] OK: every local include in {len(files)} assembled files resolves")
PY

# The scan above only proves files EXIST. It cannot see an API that moved: on
# 2026-09-17 pin 134a35cf2 made common_context_seq_rm static and gave
# mtmd_helper_bitmap_init_from_buf a fifth parameter, while rn-completion.cpp,
# rn-slot.cpp and rn-mtmd.hpp -- which never come from the fork -- kept calling
# the old ones. Every file resolved; the NDK still failed.
#
# So also PARSE the sources the Android build actually compiles -- with the
# clang that build uses. -fsyntax-only does not codegen, but it does resolve
# declarations against the NDK's own headers, and the host clang accepts
# constructs the NDK rejects: cpp/jsi/JSIParams.cpp parsed on host and broke
# the arm64 build on 2026-09-17. A host pass is weaker, not equivalent, so the
# OK line names the compiler that ran. Env:
#   ANDROID_NDK_HOME / ANDROID_NDK_ROOT  NDK location (else the homebrew path)
#   KALSA_GATE_ANDROID_API               target API (default 33, the app's
#                                        minSdkVersion in app.config.js)
#   KALSA_GATE_SYNTAX_CXX=host           force the host fallback (debugging)
#   KALSA_GATE_REQUIRE_NDK=1             a fallback is a failure, not a pass
#                                        (CI sets it: the runners have an NDK)
# llama.rn's android/gradle.properties RNLlama_ndkversion is the best declared
# candidate for the toolchain that compiles cpp/, but it is a FALLBACK, not a
# guarantee: android/build.gradle:130 takes `getExtOrDefault("ndkVersion")`, so
# a root project that sets ext.ndkVersion wins -- and this app does, through
# AGP/Expo (android/app/build.gradle:89 reads that ext, and a local build
# resolved 27.1.12297006 while this property says 27.3.13750724). The gate
# follows the property, prints the revision it really used, and the two numbers
# get compared in one CI log before anything is pinned.
NDK_API="${KALSA_GATE_ANDROID_API:-33}"
NDK_VER="${KALSA_GATE_NDK_VERSION:-}"
ENGINE_PIN=""
if [ -f "$ROOT/node_modules/llama.rn/android/gradle.properties" ]; then
  ENGINE_PIN="$(sed -n 's/^RNLlama_ndkversion=//p' \
    "$ROOT/node_modules/llama.rn/android/gradle.properties" | tr -d '[:space:]')"
fi
[ -n "$NDK_VER" ] || NDK_VER="$ENGINE_PIN"
SYNTAX_CXX=""
NDK_ROOT_USED=""
NDK_WHY="no NDK directory (\$ANDROID_HOME/ndk, \$ANDROID_SDK_ROOT/ndk, ANDROID_NDK_HOME, ANDROID_NDK_ROOT, /opt/homebrew/share/android-ndk)"

ndk_try() {  # ndk_try <ndk root> -- sets SYNTAX_CXX when the wrapper is there
  [ -n "${1:-}" ] || return 1
  if [ ! -d "$1" ]; then
    return 1
  fi
  local prebuilt found=0
  for prebuilt in "$1"/toolchains/llvm/prebuilt/*; do
    # An unexpanded glob is a string, not a directory.
    [ -d "$prebuilt" ] || continue
    found=1
    if [ -x "$prebuilt/bin/aarch64-linux-android${NDK_API}-clang++" ]; then
      SYNTAX_CXX="$prebuilt/bin/aarch64-linux-android${NDK_API}-clang++"
      NDK_ROOT_USED="$1"
      return 0
    fi
    if [ -e "$prebuilt/bin/aarch64-linux-android${NDK_API}-clang++" ]; then
      NDK_WHY="$1 has aarch64-linux-android${NDK_API}-clang++ but it is not executable"
      return 1
    fi
  done
  if [ "$found" -eq 0 ]; then
    NDK_WHY="$1 has no toolchains/llvm/prebuilt/*"
  else
    NDK_WHY="$1 has no aarch64-linux-android${NDK_API}-clang++ (API $NDK_API)"
  fi
  return 1
}

if [ "${KALSA_GATE_SYNTAX_CXX:-}" = "host" ]; then
  NDK_WHY="KALSA_GATE_SYNTAX_CXX=host"
else
  if [ -n "$NDK_VER" ]; then
    ndk_try "${ANDROID_HOME:-}/ndk/$NDK_VER" || ndk_try "${ANDROID_SDK_ROOT:-}/ndk/$NDK_VER" || true
    [ -n "$SYNTAX_CXX" ] || NDK_WHY="NDK $NDK_VER (the engine's pin) is not installed under \$ANDROID_HOME/ndk or \$ANDROID_SDK_ROOT/ndk"
  fi
  if [ -z "$SYNTAX_CXX" ] && [ "${KALSA_GATE_REQUIRE_NDK:-}" != "1" ]; then
    ndk_try "${ANDROID_NDK_HOME:-}" || ndk_try "${ANDROID_NDK_ROOT:-}" \
      || ndk_try /opt/homebrew/share/android-ndk || true
  fi
fi

# A missing compiler used to print a NOTE and exit 0: a gate that parsed
# nothing reported success, and the coverage floor below never ran.
if [ -n "$SYNTAX_CXX" ]; then
  ndk_rev="$(sed -n 's/^Pkg.Revision *= *//p' "$NDK_ROOT_USED/source.properties" 2>/dev/null | tr -d '[:space:]')"
  CXX_TAG="ndk ${ndk_rev:-unknown} api $NDK_API"
  if [ -n "$ENGINE_PIN" ] && [ "$ndk_rev" != "$ENGINE_PIN" ]; then
    CXX_TAG="$CXX_TAG, NOT the engine's pin $ENGINE_PIN"
  fi
elif [ "${KALSA_GATE_REQUIRE_NDK:-}" = "1" ]; then
  echo "[includes] FAIL: KALSA_GATE_REQUIRE_NDK=1 and the NDK clang is unusable: $NDK_WHY" >&2
  exit 1
elif command -v clang++ >/dev/null 2>&1; then
  SYNTAX_CXX="clang++"
  CXX_TAG="host clang"
else
  echo "[includes] FAIL: no compiler for the syntax pass ($NDK_WHY, and no clang++ on PATH)." >&2
  echo "[includes] The file scan alone cannot see an API that moved: it is not a pass." >&2
  exit 1
fi
echo "[includes] syntax pass compiler: $SYNTAX_CXX"

# GNU mktemp rejects a -t template without X's, so the BSD spelling fails on
# a Linux runner: give the template the X's both accept.
SYNTAX_LOG="$(mktemp "${TMPDIR:-/tmp}/kalsa-syntax.XXXXXX")"
trap 'rm -f "$SYNTAX_LOG"' EXIT

fails=0
c_common=0
c_mtmd=0
c_rn=0
parse_one() {  # parse_one <file> [extra compiler arg...]
  local f="$1"; shift
  if ! "$SYNTAX_CXX" -std=c++17 -fsyntax-only \
      -I "$CPP" \
      -I "$VENDOR" -I "$VENDOR/include" -I "$VENDOR/src" -I "$VENDOR/common" \
      -I "$VENDOR/ggml/include" -I "$VENDOR/ggml/src" -I "$VENDOR/ggml/src/ggml-cpu" \
      -I "$VENDOR/tools/mtmd" -I "$VENDOR/vendor" -I "$VENDOR/vendor/hash" \
      -I "$CODEC/include" -I "$CODEC/common" \
      ${@+"$@"} \
      "$f" > "$SYNTAX_LOG" 2>&1; then
    echo "[includes] SYNTAX FAIL: $(basename "$f")"
    # `| head` sends SIGPIPE and a grep that matches nothing exits 1: under
    # `set -e` either one would kill the script before it printed why.
    (grep -E "error:" "$SYNTAX_LOG" || tail -3 "$SYNTAX_LOG") 2>/dev/null \
      | sed -n '1,3p' | sed 's/^/    /' || true
    fails=$((fails + 1))
  fi
}

for f in "$VENDOR"/common/*.cpp "$VENDOR"/tools/mtmd/*.cpp; do
  # An unmatched glob is a string, not a file: skipping it silently is how this
  # gate would print OK on an engine that lost the sources it is here to check.
  [ -f "$f" ] || continue
  case " $EXCLUDED " in *" $(basename "$f") "*) continue ;; esac
  case "$f" in
    "$VENDOR"/common/*) c_common=$((c_common + 1)) ;;
    *) c_mtmd=$((c_mtmd + 1)) ;;
  esac
  parse_one "$f"
done
# The rn-owned sources are compiled with the backends the app turns on
# (app.config.js `enableOpenCLAndHexagon: true` -> ENABLE_OPENCL in the fork's
# CMakeLists), and rn-slot.cpp guards three blocks on LM_GGML_USE_OPENCL. Parsed
# without the define, those blocks are invisible to this gate and the drift in
# them surfaces only in the APK build.
for f in "$CPP"/rn-*.cpp; do
  [ -f "$f" ] || continue
  c_rn=$((c_rn + 1))
  parse_one "$f" -DLM_GGML_USE_OPENCL
done

parsed=$((c_common + c_mtmd + c_rn))
# One floor per group, not one total: with a single total a whole group can
# vanish and the OK line still claims to have covered it.
# Close to today's counts (7 rn, 20 common, 5 mtmd), not a token threshold: a
# floor of 15 on common would let a quarter of the group vanish unnoticed.
if [ "$c_rn" -lt 7 ] || [ "$c_common" -lt 18 ] || [ "$c_mtmd" -lt 5 ]; then
  echo "[includes] FAIL: parsed $c_common common, $c_mtmd mtmd, $c_rn rn-* sources."
  echo "[includes] The installed engine is missing sources this gate must cover."
  exit 1
fi
if [ "$fails" -gt 0 ]; then
  echo "[includes] $fails source(s) do not parse against the assembled tree."
  echo "[includes] An API the engine moved, or a header the flatten did not bring."
  exit 1
fi
# Not "everything the build compiles": this parses vendor/llama.cpp/common/,
# vendor/llama.cpp/tools/mtmd/ and the rn-owned sources in cpp/ -- the drift
# surface between the engine and the binding. The rest is covered by the fork's
# own gates (assert-kalsa-vendor.sh and assert-rnllama-sources.sh in
# Aspis0/kalsa.rn, run by its `vendor` CI job), which run there, not here.
echo "[includes] OK [$CXX_TAG]: $parsed source(s) parse ($c_common common, $c_mtmd mtmd, $c_rn rn-* with -DLM_GGML_USE_OPENCL)"
