#!/usr/bin/env bash
# Every local #include in the assembled engine must resolve to a file on disk.
#
# The engine is installed from the fork Aspis0/llama.rn, whose cpp/ is built by
# flattening kalsallama through an explicit ALLOW-LIST (the fork's
# scripts/sync-kalsallama.sh, copy_src / copy_common). When upstream adds a file
# and an existing source starts including it, the list does not learn: the
# header is simply absent and the NDK fails ~5 minutes into the APK build, far
# from the commit that caused it. That is how
#   common/peg-parser.h:3:10: fatal error: 'json.h' file not found
# reached CI on 2026-09-17 — json.h/json.cpp, plus llama-kv-cache-dsa-iswa,
# llama-kv-cache-msa and llama-memory-hybrid-idx, all existed in the fork and
# none were on the list.
#
# This gate runs in seconds and fails at the point of assembly instead.
# Conditional backend includes (CUDA, Vulkan, …) and build-generated headers
# are listed as known-absent; anything else is a missing vendor file.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CPP="$ROOT/node_modules/llama.rn/cpp"
[ -d "$CPP" ] || { echo "[includes] missing $CPP — run npm install" >&2; exit 1; }

python3 - "$CPP" <<'PY'
import os, re, sys, glob

cpp = sys.argv[1]
os.chdir(cpp)

# Guarded by #ifdef for a backend we never build, or emitted by the build.
KNOWN_ABSENT = {
    "ggml-cann.h", "ggml-cuda.h", "ggml-et.h", "ggml-openvino.h", "ggml-rpc.h",
    "ggml-sycl.h", "ggml-virtgpu.h", "ggml-vulkan.h", "ggml-webgpu.h",
    "ggml-zdnn.h", "ggml-zendnn.h",
    "llama-version.h",          # generated by the build
    "bmoe_stream.h",            # MoE stream port, guarded
    "sheredom/subprocess.h",    # mtmd-helper.cpp, behind #ifdef MTMD_VIDEO
}
SEARCH = ["", "common", "common/jinja", "tools/mtmd", "nlohmann"]

files = []
for pat in ("*.h", "*.cpp", "common/*.h", "common/*.cpp",
            "common/jinja/*.h", "common/jinja/*.cpp",
            "jsi/*.h", "jsi/*.cpp", "tools/mtmd/*.h", "tools/mtmd/*.cpp"):
    files += glob.glob(pat)

missing = {}
for f in files:
    with open(f, errors="ignore") as fh:
        body = fh.read()
    for m in re.finditer(r'^\s*#\s*include\s+"([^"]+)"', body, re.M):
        inc = m.group(1)
        if inc in KNOWN_ABSENT:
            continue
        here = os.path.join(os.path.dirname(f), inc)
        if os.path.exists(here) or any(os.path.exists(os.path.join(d, inc)) for d in SEARCH):
            continue
        missing.setdefault(inc, []).append(f)

if missing:
    print(f"[includes] FAIL: {len(missing)} unresolved include(s) in the assembled engine")
    for inc, users in sorted(missing.items()):
        print(f"  {inc}  <- {', '.join(sorted(users)[:4])}")
    print("[includes] in the fork: add the file to copy_src/copy_common in")
    print("[includes] scripts/sync-kalsallama.sh, re-run `sync-kalsallama.sh pin <sha>`, push,")
    print("[includes] then move the app to the new fork sha and `npm install`.")
    raise SystemExit(1)

print(f"[includes] OK: every local include in {len(files)} assembled files resolves")
PY

# The scan above only proves files EXIST. It cannot see an API that moved: on
# 2026-09-17 pin 134a35cf2 made common_context_seq_rm static and gave
# mtmd_helper_bitmap_init_from_buf a fifth parameter, while rn-completion.cpp,
# rn-slot.cpp and rn-mtmd.hpp -- which never come from the fork -- kept calling
# the old ones. Every file resolved; the NDK still failed.
#
# So also PARSE the sources the Android build actually compiles -- with the
# clang that build uses. -fsyntax-only does not codegen, but it does resolve
# declarations against the NDK's own headers, and the host clang accepts
# constructs the NDK rejects: cpp/jsi/JSIParams.cpp parsed on host and broke
# the arm64 build on 2026-09-17. A host pass is weaker, not equivalent, so the
# OK line names the compiler that ran. Env:
#   ANDROID_NDK_HOME / ANDROID_NDK_ROOT  NDK location (else the homebrew path)
#   KALSA_GATE_ANDROID_API               target API (default 33, the app's
#                                        minSdkVersion in app.config.js)
#   KALSA_GATE_SYNTAX_CXX=host           force the host fallback (debugging)
#   KALSA_GATE_REQUIRE_NDK=1             a fallback is a failure, not a pass
#                                        (CI sets it: the runners have an NDK)
# The engine module declares the NDK its own build uses -- llama.rn's
# android/gradle.properties RNLlama_ndkversion, read at android/build.gradle:133
# as `ndkVersion` -- so the gate can parse with that exact toolchain instead of
# whatever NDK happens to be installed. The app itself declares none (its
# ndkVersion comes from AGP's default), which is why the engine's pin is the
# number worth following.
NDK_API="${KALSA_GATE_ANDROID_API:-33}"
NDK_VER="${KALSA_GATE_NDK_VERSION:-}"
ENGINE_PIN=""
if [ -f "$ROOT/node_modules/llama.rn/android/gradle.properties" ]; then
  ENGINE_PIN="$(sed -n 's/^RNLlama_ndkversion=//p' \
    "$ROOT/node_modules/llama.rn/android/gradle.properties" | tr -d '[:space:]')"
fi
[ -n "$NDK_VER" ] || NDK_VER="$ENGINE_PIN"
SYNTAX_CXX=""
NDK_ROOT_USED=""
NDK_WHY="no NDK directory (\$ANDROID_HOME/ndk, \$ANDROID_SDK_ROOT/ndk, ANDROID_NDK_HOME, ANDROID_NDK_ROOT, /opt/homebrew/share/android-ndk)"

ndk_try() {  # ndk_try <ndk root> -- sets SYNTAX_CXX when the wrapper is there
  [ -n "${1:-}" ] || return 1
  if [ ! -d "$1" ]; then
    return 1
  fi
  local prebuilt found=0
  for prebuilt in "$1"/toolchains/llvm/prebuilt/*; do
    # An unexpanded glob is a string, not a directory.
    [ -d "$prebuilt" ] || continue
    found=1
    if [ -x "$prebuilt/bin/aarch64-linux-android${NDK_API}-clang++" ]; then
      SYNTAX_CXX="$prebuilt/bin/aarch64-linux-android${NDK_API}-clang++"
      NDK_ROOT_USED="$1"
      return 0
    fi
    if [ -e "$prebuilt/bin/aarch64-linux-android${NDK_API}-clang++" ]; then
      NDK_WHY="$1 has aarch64-linux-android${NDK_API}-clang++ but it is not executable"
      return 1
    fi
  done
  if [ "$found" -eq 0 ]; then
    NDK_WHY="$1 has no toolchains/llvm/prebuilt/*"
  else
    NDK_WHY="$1 has no aarch64-linux-android${NDK_API}-clang++ (API $NDK_API)"
  fi
  return 1
}

if [ "${KALSA_GATE_SYNTAX_CXX:-}" = "host" ]; then
  NDK_WHY="KALSA_GATE_SYNTAX_CXX=host"
else
  if [ -n "$NDK_VER" ]; then
    ndk_try "${ANDROID_HOME:-}/ndk/$NDK_VER" || ndk_try "${ANDROID_SDK_ROOT:-}/ndk/$NDK_VER" || true
    [ -n "$SYNTAX_CXX" ] || NDK_WHY="NDK $NDK_VER (the engine's pin) is not installed under \$ANDROID_HOME/ndk or \$ANDROID_SDK_ROOT/ndk"
  fi
  if [ -z "$SYNTAX_CXX" ] && [ "${KALSA_GATE_REQUIRE_NDK:-}" != "1" ]; then
    ndk_try "${ANDROID_NDK_HOME:-}" || ndk_try "${ANDROID_NDK_ROOT:-}" \
      || ndk_try /opt/homebrew/share/android-ndk || true
  fi
fi

# A missing compiler used to print a NOTE and exit 0: a gate that parsed
# nothing reported success, and the coverage floor below never ran.
if [ -n "$SYNTAX_CXX" ]; then
  ndk_rev="$(sed -n 's/^Pkg.Revision *= *//p' "$NDK_ROOT_USED/source.properties" 2>/dev/null | tr -d '[:space:]')"
  CXX_TAG="ndk ${ndk_rev:-unknown} api $NDK_API"
  if [ -n "$ENGINE_PIN" ] && [ "$ndk_rev" != "$ENGINE_PIN" ]; then
    CXX_TAG="$CXX_TAG, NOT the engine's pin $ENGINE_PIN"
  fi
elif [ "${KALSA_GATE_REQUIRE_NDK:-}" = "1" ]; then
  echo "[includes] FAIL: KALSA_GATE_REQUIRE_NDK=1 and the NDK clang is unusable: $NDK_WHY" >&2
  exit 1
elif command -v clang++ >/dev/null 2>&1; then
  SYNTAX_CXX="clang++"
  CXX_TAG="host clang"
else
  echo "[includes] FAIL: no compiler for the syntax pass ($NDK_WHY, and no clang++ on PATH)." >&2
  echo "[includes] The file scan alone cannot see an API that moved: it is not a pass." >&2
  exit 1
fi
echo "[includes] syntax pass compiler: $SYNTAX_CXX"

# GNU mktemp rejects a -t template without X's, so the BSD spelling fails on
# a Linux runner: give the template the X's both accept.
SYNTAX_LOG="$(mktemp "${TMPDIR:-/tmp}/kalsa-syntax.XXXXXX")"
trap 'rm -f "$SYNTAX_LOG"' EXIT

fails=0
c_common=0
c_mtmd=0
c_rn=0
parse_one() {  # parse_one <file> [extra compiler arg...]
  local f="$1"; shift
  if ! "$SYNTAX_CXX" -std=c++17 -fsyntax-only \
      -I "$CPP" -I "$CPP/common" -I "$CPP/common/jinja" \
      -I "$CPP/ggml-cpu" -I "$CPP/tools/mtmd" -I "$ROOT/native/bmoe/rn" \
      ${@+"$@"} \
      "$f" > "$SYNTAX_LOG" 2>&1; then
    echo "[includes] SYNTAX FAIL: $(basename "$f")"
    # `| head` sends SIGPIPE and a grep that matches nothing exits 1: under
    # `set -e` either one would kill the script before it printed why.
    (grep -E "error:" "$SYNTAX_LOG" || tail -3 "$SYNTAX_LOG") 2>/dev/null \
      | sed -n '1,3p' | sed 's/^/    /' || true
    fails=$((fails + 1))
  fi
}

for f in "$CPP"/common/*.cpp "$CPP"/tools/mtmd/*.cpp; do
  # An unmatched glob is a string, not a file: skipping it silently is how this
  # gate would print OK on an engine that lost the sources it is here to check.
  [ -f "$f" ] || continue
  case "$f" in
    "$CPP"/common/*) c_common=$((c_common + 1)) ;;
    *) c_mtmd=$((c_mtmd + 1)) ;;
  esac
  parse_one "$f"
done
# The rn-owned sources are compiled with the backends the app turns on
# (app.config.js `enableOpenCLAndHexagon: true` -> ENABLE_OPENCL in the fork's
# CMakeLists), and rn-slot.cpp guards three blocks on LM_GGML_USE_OPENCL. Parsed
# without the define, those blocks are invisible to this gate and the drift in
# them surfaces only in the APK build.
for f in "$CPP"/rn-*.cpp; do
  [ -f "$f" ] || continue
  c_rn=$((c_rn + 1))
  parse_one "$f" -DLM_GGML_USE_OPENCL
done

parsed=$((c_common + c_mtmd + c_rn))
# One floor per group, not one total: with a single total a whole group can
# vanish and the OK line still claims to have covered it.
if [ "$c_rn" -lt 5 ] || [ "$c_common" -lt 15 ] || [ "$c_mtmd" -lt 3 ]; then
  echo "[includes] FAIL: parsed $c_common common, $c_mtmd mtmd, $c_rn rn-* sources."
  echo "[includes] The installed engine is missing sources this gate must cover."
  exit 1
fi
if [ "$fails" -gt 0 ]; then
  echo "[includes] $fails source(s) do not parse against the assembled tree."
  echo "[includes] An API the engine moved, or a header the flatten did not bring."
  exit 1
fi
# Not "everything the build compiles": this parses common/, tools/mtmd/ and the
# rn-owned sources -- the drift surface between the engine and the binding. The
# rest of cpp/ is covered by the fork's own gate (scripts/assert-cpp-includes.sh
# in Aspis0/llama.rn, 307 TUs), which runs there, not here.
echo "[includes] OK [$CXX_TAG]: $parsed source(s) parse ($c_common common, $c_mtmd mtmd, $c_rn rn-* with -DLM_GGML_USE_OPENCL)"
