#!/usr/bin/env bash
# Every local #include in the assembled engine must resolve to a file on disk.
#
# The engine is installed from the fork Aspis0/llama.rn, whose cpp/ is built by
# flattening kalsallama through an explicit ALLOW-LIST (the fork's
# scripts/sync-kalsallama.sh, copy_src / copy_common). When upstream adds a file
# and an existing source starts including it, the list does not learn: the
# header is simply absent and the NDK fails ~5 minutes into the APK build, far
# from the commit that caused it. That is how
#   common/peg-parser.h:3:10: fatal error: 'json.h' file not found
# reached CI on 2026-09-17 — json.h/json.cpp, plus llama-kv-cache-dsa-iswa,
# llama-kv-cache-msa and llama-memory-hybrid-idx, all existed in the fork and
# none were on the list.
#
# This gate runs in seconds and fails at the point of assembly instead.
# Conditional backend includes (CUDA, Vulkan, …) and build-generated headers
# are listed as known-absent; anything else is a missing vendor file.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CPP="$ROOT/node_modules/llama.rn/cpp"
[ -d "$CPP" ] || { echo "[includes] missing $CPP — run npm install" >&2; exit 1; }

python3 - "$CPP" <<'PY'
import os, re, sys, glob

cpp = sys.argv[1]
os.chdir(cpp)

# Guarded by #ifdef for a backend we never build, or emitted by the build.
KNOWN_ABSENT = {
    "ggml-cann.h", "ggml-cuda.h", "ggml-et.h", "ggml-openvino.h", "ggml-rpc.h",
    "ggml-sycl.h", "ggml-virtgpu.h", "ggml-vulkan.h", "ggml-webgpu.h",
    "ggml-zdnn.h", "ggml-zendnn.h",
    "llama-version.h",          # generated by the build
    "bmoe_stream.h",            # MoE stream port, guarded
    "sheredom/subprocess.h",    # mtmd-helper.cpp, behind #ifdef MTMD_VIDEO
}
SEARCH = ["", "common", "common/jinja", "tools/mtmd", "nlohmann"]

files = []
for pat in ("*.h", "*.cpp", "common/*.h", "common/*.cpp",
            "common/jinja/*.h", "common/jinja/*.cpp",
            "jsi/*.h", "jsi/*.cpp", "tools/mtmd/*.h", "tools/mtmd/*.cpp"):
    files += glob.glob(pat)

missing = {}
for f in files:
    with open(f, errors="ignore") as fh:
        body = fh.read()
    for m in re.finditer(r'^\s*#\s*include\s+"([^"]+)"', body, re.M):
        inc = m.group(1)
        if inc in KNOWN_ABSENT:
            continue
        here = os.path.join(os.path.dirname(f), inc)
        if os.path.exists(here) or any(os.path.exists(os.path.join(d, inc)) for d in SEARCH):
            continue
        missing.setdefault(inc, []).append(f)

if missing:
    print(f"[includes] FAIL: {len(missing)} unresolved include(s) in the assembled engine")
    for inc, users in sorted(missing.items()):
        print(f"  {inc}  <- {', '.join(sorted(users)[:4])}")
    print("[includes] in the fork: add the file to copy_src/copy_common in")
    print("[includes] scripts/sync-kalsallama.sh, re-run `sync-kalsallama.sh pin <sha>`, push,")
    print("[includes] then move the app to the new fork sha and `npm install`.")
    raise SystemExit(1)

print(f"[includes] OK: every local include in {len(files)} assembled files resolves")
PY

# The scan above only proves files EXIST. It cannot see an API that moved: on
# 2026-09-17 pin 134a35cf2 made common_context_seq_rm static and gave
# mtmd_helper_bitmap_init_from_buf a fifth parameter, while rn-completion.cpp,
# rn-slot.cpp and rn-mtmd.hpp -- which never come from the fork -- kept calling
# the old ones. Every file resolved; the NDK still failed.
#
# So also PARSE the sources the Android build actually compiles -- with the
# clang that build uses. -fsyntax-only does not codegen, but it does resolve
# declarations against the NDK's own headers, and the host clang accepts
# constructs the NDK rejects: cpp/jsi/JSIParams.cpp parsed on host and broke
# the arm64 build on 2026-09-17. A host pass is weaker, not equivalent, so the
# OK line names the compiler that ran. Env:
#   ANDROID_NDK_HOME / ANDROID_NDK_ROOT  NDK location (else the homebrew path)
#   KALSA_GATE_ANDROID_API               target API (default 33, the app's
#                                        minSdkVersion in app.config.js)
#   KALSA_GATE_SYNTAX_CXX=host           force the host fallback (debugging)
#   KALSA_GATE_REQUIRE_NDK=1             a fallback is a failure, not a pass
#                                        (CI sets it: the runners have an NDK)
NDK_API="${KALSA_GATE_ANDROID_API:-33}"
SYNTAX_CXX=""
NDK_WHY="no NDK directory (ANDROID_NDK_HOME, ANDROID_NDK_ROOT, /opt/homebrew/share/android-ndk)"
if [ "${KALSA_GATE_SYNTAX_CXX:-}" = "host" ]; then
  NDK_WHY="KALSA_GATE_SYNTAX_CXX=host"
else
  for ndk_root in "${ANDROID_NDK_HOME:-}" "${ANDROID_NDK_ROOT:-}" \
                  /opt/homebrew/share/android-ndk; do
    [ -d "$ndk_root" ] || continue
    for prebuilt in "$ndk_root"/toolchains/llvm/prebuilt/*; do
      # An unexpanded glob is a string, not a directory.
      [ -d "$prebuilt" ] || continue
      if [ -x "$prebuilt/bin/aarch64-linux-android${NDK_API}-clang++" ]; then
        SYNTAX_CXX="$prebuilt/bin/aarch64-linux-android${NDK_API}-clang++"
        break 2
      fi
      NDK_WHY="$ndk_root has no aarch64-linux-android${NDK_API}-clang++"
    done
  done
fi

# A missing compiler used to print a NOTE and exit 0: a gate that parsed
# nothing reported success, and the coverage floor below never ran.
if [ -n "$SYNTAX_CXX" ]; then
  CXX_TAG="ndk aarch64-linux-android${NDK_API}"
elif [ "${KALSA_GATE_REQUIRE_NDK:-}" = "1" ]; then
  echo "[includes] FAIL: KALSA_GATE_REQUIRE_NDK=1 and the NDK clang is unusable: $NDK_WHY" >&2
  exit 1
elif command -v clang++ >/dev/null 2>&1; then
  SYNTAX_CXX="clang++"
  CXX_TAG="host clang"
else
  echo "[includes] FAIL: no compiler for the syntax pass ($NDK_WHY, and no clang++ on PATH)." >&2
  echo "[includes] The file scan alone cannot see an API that moved: it is not a pass." >&2
  exit 1
fi
echo "[includes] syntax pass compiler: $SYNTAX_CXX"

fails=0
parsed=0
rn_parsed=0
for f in "$CPP"/common/*.cpp "$CPP"/tools/mtmd/*.cpp "$CPP"/rn-*.cpp; do
  # An unmatched glob is a string, not a file: skipping it silently is how this
  # gate would print OK on an engine that lost the sources it is here to check.
  [ -f "$f" ] || continue
  parsed=$((parsed + 1))
  case "$(basename "$f")" in rn-*) rn_parsed=$((rn_parsed + 1)) ;; esac
  if ! "$SYNTAX_CXX" -std=c++17 -fsyntax-only \
      -I "$CPP" -I "$CPP/common" -I "$CPP/common/jinja" \
      -I "$CPP/ggml-cpu" -I "$CPP/tools/mtmd" -I "$ROOT/native/bmoe/rn" \
      "$f" > /tmp/kalsa-syntax.log 2>&1; then
    echo "[includes] SYNTAX FAIL: $(basename "$f")"
    grep -E "error:" /tmp/kalsa-syntax.log | head -3 | sed 's/^/    /'
    fails=$((fails + 1))
  fi
done
if [ "$rn_parsed" -eq 0 ] || [ "$parsed" -lt 20 ]; then
  echo "[includes] FAIL: only $parsed source(s) parsed, $rn_parsed of them rn-*."
  echo "[includes] The installed engine is missing sources this gate must cover."
  exit 1
fi
if [ "$fails" -gt 0 ]; then
  echo "[includes] $fails source(s) do not parse against the assembled tree."
  echo "[includes] An API the engine moved, or a header the flatten did not bring."
  exit 1
fi
# Not "everything the build compiles": this parses common/, tools/mtmd/ and the
# rn-owned sources -- the drift surface between the engine and the binding. The
# rest of cpp/ is the fork's own gate (scripts/assert-cpp-includes.sh, 307 TUs).
echo "[includes] OK [$CXX_TAG]: $parsed source(s) parse ($rn_parsed rn-*): common, mtmd, rn-*"
